/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables;


import com.verint.mpathy.db.live_core.LiveCore;
import com.verint.mpathy.db.live_core.tables.records.MapClickPathinfo_11024Record;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapClickPathinfo_11024 extends TableImpl<MapClickPathinfo_11024Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live_core.map_click_pathinfo_11024</code>
     */
    public static final MapClickPathinfo_11024 MAP_CLICK_PATHINFO_11024 = new MapClickPathinfo_11024();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapClickPathinfo_11024Record> getRecordType() {
        return MapClickPathinfo_11024Record.class;
    }

    /**
     * The column
     * <code>live_core.map_click_pathinfo_11024.idpathinfo_plain</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, String> IDPATHINFO_PLAIN = createField(DSL.name("idpathinfo_plain"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.idpage_name</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Long> IDPAGE_NAME = createField(DSL.name("idpage_name"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.idsite</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> IDSITE = createField(DSL.name("idsite"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.abs_width</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> ABS_WIDTH = createField(DSL.name("abs_width"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.abs_height</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> ABS_HEIGHT = createField(DSL.name("abs_height"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.abs_x</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> ABS_X = createField(DSL.name("abs_x"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.abs_y</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> ABS_Y = createField(DSL.name("abs_y"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.rel_x</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> REL_X = createField(DSL.name("rel_x"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.rel_y</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Integer> REL_Y = createField(DSL.name("rel_y"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.relp_width</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, BigDecimal> RELP_WIDTH = createField(DSL.name("relp_width"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.relp_x</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, BigDecimal> RELP_X = createField(DSL.name("relp_x"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo_11024.idpathinfo</code>.
     */
    public final TableField<MapClickPathinfo_11024Record, Long> IDPATHINFO = createField(DSL.name("idpathinfo"), SQLDataType.BIGINT, this, "");

    private MapClickPathinfo_11024(Name alias, Table<MapClickPathinfo_11024Record> aliased) {
        this(alias, aliased, null);
    }

    private MapClickPathinfo_11024(Name alias, Table<MapClickPathinfo_11024Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Easy access to underlying table in other schemas."), TableOptions.view("create view \"map_click_pathinfo_11024\" as  SELECT map_click_pathinfo_11024.idpathinfo_plain,\n    map_click_pathinfo_11024.idpage_name,\n    map_click_pathinfo_11024.idsite,\n    map_click_pathinfo_11024.abs_width,\n    map_click_pathinfo_11024.abs_height,\n    map_click_pathinfo_11024.abs_x,\n    map_click_pathinfo_11024.abs_y,\n    map_click_pathinfo_11024.rel_x,\n    map_click_pathinfo_11024.rel_y,\n    map_click_pathinfo_11024.relp_width,\n    map_click_pathinfo_11024.relp_x,\n    map_click_pathinfo_11024.idpathinfo\n   FROM live.map_click_pathinfo_11024;"));
    }

    /**
     * Create an aliased <code>live_core.map_click_pathinfo_11024</code> table
     * reference
     */
    public MapClickPathinfo_11024(String alias) {
        this(DSL.name(alias), MAP_CLICK_PATHINFO_11024);
    }

    /**
     * Create an aliased <code>live_core.map_click_pathinfo_11024</code> table
     * reference
     */
    public MapClickPathinfo_11024(Name alias) {
        this(alias, MAP_CLICK_PATHINFO_11024);
    }

    /**
     * Create a <code>live_core.map_click_pathinfo_11024</code> table reference
     */
    public MapClickPathinfo_11024() {
        this(DSL.name("map_click_pathinfo_11024"), null);
    }

    public <O extends Record> MapClickPathinfo_11024(Table<O> child, ForeignKey<O, MapClickPathinfo_11024Record> key) {
        super(child, key, MAP_CLICK_PATHINFO_11024);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : LiveCore.LIVE_CORE;
    }

    @Override
    public MapClickPathinfo_11024 as(String alias) {
        return new MapClickPathinfo_11024(DSL.name(alias), this);
    }

    @Override
    public MapClickPathinfo_11024 as(Name alias) {
        return new MapClickPathinfo_11024(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MapClickPathinfo_11024 rename(String name) {
        return new MapClickPathinfo_11024(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MapClickPathinfo_11024 rename(Name name) {
        return new MapClickPathinfo_11024(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, Long, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
