/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables;


import com.verint.mpathy.db.live_core.LiveCore;
import com.verint.mpathy.db.live_core.tables.records.MapClickPathinfoRecord;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapClickPathinfo extends TableImpl<MapClickPathinfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live_core.map_click_pathinfo</code>
     */
    public static final MapClickPathinfo MAP_CLICK_PATHINFO = new MapClickPathinfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapClickPathinfoRecord> getRecordType() {
        return MapClickPathinfoRecord.class;
    }

    /**
     * The column <code>live_core.map_click_pathinfo.idpathinfo_plain</code>.
     */
    public final TableField<MapClickPathinfoRecord, String> IDPATHINFO_PLAIN = createField(DSL.name("idpathinfo_plain"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.idpage_name</code>.
     */
    public final TableField<MapClickPathinfoRecord, Long> IDPAGE_NAME = createField(DSL.name("idpage_name"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.idsite</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> IDSITE = createField(DSL.name("idsite"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.abs_width</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> ABS_WIDTH = createField(DSL.name("abs_width"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.abs_height</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> ABS_HEIGHT = createField(DSL.name("abs_height"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.abs_x</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> ABS_X = createField(DSL.name("abs_x"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.abs_y</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> ABS_Y = createField(DSL.name("abs_y"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.rel_x</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> REL_X = createField(DSL.name("rel_x"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.rel_y</code>.
     */
    public final TableField<MapClickPathinfoRecord, Integer> REL_Y = createField(DSL.name("rel_y"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.relp_width</code>.
     */
    public final TableField<MapClickPathinfoRecord, BigDecimal> RELP_WIDTH = createField(DSL.name("relp_width"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.relp_x</code>.
     */
    public final TableField<MapClickPathinfoRecord, BigDecimal> RELP_X = createField(DSL.name("relp_x"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>live_core.map_click_pathinfo.idpathinfo</code>.
     */
    public final TableField<MapClickPathinfoRecord, Long> IDPATHINFO = createField(DSL.name("idpathinfo"), SQLDataType.BIGINT, this, "");

    private MapClickPathinfo(Name alias, Table<MapClickPathinfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private MapClickPathinfo(Name alias, Table<MapClickPathinfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Easy access to underlying table in other schemas."), TableOptions.view("create view \"map_click_pathinfo\" as  SELECT map_click_pathinfo.idpathinfo_plain,\n    map_click_pathinfo.idpage_name,\n    map_click_pathinfo.idsite,\n    map_click_pathinfo.abs_width,\n    map_click_pathinfo.abs_height,\n    map_click_pathinfo.abs_x,\n    map_click_pathinfo.abs_y,\n    map_click_pathinfo.rel_x,\n    map_click_pathinfo.rel_y,\n    map_click_pathinfo.relp_width,\n    map_click_pathinfo.relp_x,\n    map_click_pathinfo.idpathinfo\n   FROM live.map_click_pathinfo;"));
    }

    /**
     * Create an aliased <code>live_core.map_click_pathinfo</code> table
     * reference
     */
    public MapClickPathinfo(String alias) {
        this(DSL.name(alias), MAP_CLICK_PATHINFO);
    }

    /**
     * Create an aliased <code>live_core.map_click_pathinfo</code> table
     * reference
     */
    public MapClickPathinfo(Name alias) {
        this(alias, MAP_CLICK_PATHINFO);
    }

    /**
     * Create a <code>live_core.map_click_pathinfo</code> table reference
     */
    public MapClickPathinfo() {
        this(DSL.name("map_click_pathinfo"), null);
    }

    public <O extends Record> MapClickPathinfo(Table<O> child, ForeignKey<O, MapClickPathinfoRecord> key) {
        super(child, key, MAP_CLICK_PATHINFO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : LiveCore.LIVE_CORE;
    }

    @Override
    public MapClickPathinfo as(String alias) {
        return new MapClickPathinfo(DSL.name(alias), this);
    }

    @Override
    public MapClickPathinfo as(Name alias) {
        return new MapClickPathinfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MapClickPathinfo rename(String name) {
        return new MapClickPathinfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MapClickPathinfo rename(Name name) {
        return new MapClickPathinfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, Long, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
