/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables;


import com.verint.mpathy.db.live_core.LiveCore;
import com.verint.mpathy.db.live_core.tables.records.PropertyValuesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertyValues extends TableImpl<PropertyValuesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live_core.property_values</code>
     */
    public static final PropertyValues PROPERTY_VALUES = new PropertyValues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PropertyValuesRecord> getRecordType() {
        return PropertyValuesRecord.class;
    }

    /**
     * The column <code>live_core.property_values.idvalue</code>.
     */
    public final TableField<PropertyValuesRecord, Long> IDVALUE = createField(DSL.name("idvalue"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>live_core.property_values.content</code>.
     */
    public final TableField<PropertyValuesRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    private PropertyValues(Name alias, Table<PropertyValuesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PropertyValues(Name alias, Table<PropertyValuesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Easy access to underlying table in other schemas."), TableOptions.view("create view \"property_values\" as  SELECT property_values.idvalue,\n    property_values.content\n   FROM live.property_values;"));
    }

    /**
     * Create an aliased <code>live_core.property_values</code> table reference
     */
    public PropertyValues(String alias) {
        this(DSL.name(alias), PROPERTY_VALUES);
    }

    /**
     * Create an aliased <code>live_core.property_values</code> table reference
     */
    public PropertyValues(Name alias) {
        this(alias, PROPERTY_VALUES);
    }

    /**
     * Create a <code>live_core.property_values</code> table reference
     */
    public PropertyValues() {
        this(DSL.name("property_values"), null);
    }

    public <O extends Record> PropertyValues(Table<O> child, ForeignKey<O, PropertyValuesRecord> key) {
        super(child, key, PROPERTY_VALUES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : LiveCore.LIVE_CORE;
    }

    @Override
    public PropertyValues as(String alias) {
        return new PropertyValues(DSL.name(alias), this);
    }

    @Override
    public PropertyValues as(Name alias) {
        return new PropertyValues(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PropertyValues rename(String name) {
        return new PropertyValues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PropertyValues rename(Name name) {
        return new PropertyValues(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
