/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables;


import com.verint.mpathy.db.live_core.LiveCore;
import com.verint.mpathy.db.live_core.tables.records.QuestionnaireLayoutRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuestionnaireLayout extends TableImpl<QuestionnaireLayoutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live_core.questionnaire_layout</code>
     */
    public static final QuestionnaireLayout QUESTIONNAIRE_LAYOUT = new QuestionnaireLayout();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuestionnaireLayoutRecord> getRecordType() {
        return QuestionnaireLayoutRecord.class;
    }

    /**
     * The column
     * <code>live_core.questionnaire_layout.idquestionnaire_layout</code>.
     */
    public final TableField<QuestionnaireLayoutRecord, Long> IDQUESTIONNAIRE_LAYOUT = createField(DSL.name("idquestionnaire_layout"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>live_core.questionnaire_layout.idsite</code>.
     */
    public final TableField<QuestionnaireLayoutRecord, Integer> IDSITE = createField(DSL.name("idsite"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>live_core.questionnaire_layout.name</code>.
     */
    public final TableField<QuestionnaireLayoutRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>live_core.questionnaire_layout.css_url</code>.
     */
    public final TableField<QuestionnaireLayoutRecord, String> CSS_URL = createField(DSL.name("css_url"), SQLDataType.CLOB, this, "");

    private QuestionnaireLayout(Name alias, Table<QuestionnaireLayoutRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuestionnaireLayout(Name alias, Table<QuestionnaireLayoutRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Easy access to underlying table in other schemas."), TableOptions.view("create view \"questionnaire_layout\" as  SELECT questionnaire_layout.idquestionnaire_layout,\n    questionnaire_layout.idsite,\n    questionnaire_layout.name,\n    questionnaire_layout.css_url\n   FROM live.questionnaire_layout;"));
    }

    /**
     * Create an aliased <code>live_core.questionnaire_layout</code> table
     * reference
     */
    public QuestionnaireLayout(String alias) {
        this(DSL.name(alias), QUESTIONNAIRE_LAYOUT);
    }

    /**
     * Create an aliased <code>live_core.questionnaire_layout</code> table
     * reference
     */
    public QuestionnaireLayout(Name alias) {
        this(alias, QUESTIONNAIRE_LAYOUT);
    }

    /**
     * Create a <code>live_core.questionnaire_layout</code> table reference
     */
    public QuestionnaireLayout() {
        this(DSL.name("questionnaire_layout"), null);
    }

    public <O extends Record> QuestionnaireLayout(Table<O> child, ForeignKey<O, QuestionnaireLayoutRecord> key) {
        super(child, key, QUESTIONNAIRE_LAYOUT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : LiveCore.LIVE_CORE;
    }

    @Override
    public QuestionnaireLayout as(String alias) {
        return new QuestionnaireLayout(DSL.name(alias), this);
    }

    @Override
    public QuestionnaireLayout as(Name alias) {
        return new QuestionnaireLayout(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestionnaireLayout rename(String name) {
        return new QuestionnaireLayout(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuestionnaireLayout rename(Name name) {
        return new QuestionnaireLayout(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
