/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables;


import com.verint.mpathy.db.live_core.LiveCore;
import com.verint.mpathy.db.live_core.tables.records.StruggleIndicatorJsErrorCountRecord;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StruggleIndicatorJsErrorCount extends TableImpl<StruggleIndicatorJsErrorCountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>live_core.struggle_indicator_js_error_count</code>
     */
    public static final StruggleIndicatorJsErrorCount STRUGGLE_INDICATOR_JS_ERROR_COUNT = new StruggleIndicatorJsErrorCount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StruggleIndicatorJsErrorCountRecord> getRecordType() {
        return StruggleIndicatorJsErrorCountRecord.class;
    }

    /**
     * The column
     * <code>live_core.struggle_indicator_js_error_count.idstruggle_indicator_js_error_count</code>.
     */
    public final TableField<StruggleIndicatorJsErrorCountRecord, Long> IDSTRUGGLE_INDICATOR_JS_ERROR_COUNT = createField(DSL.name("idstruggle_indicator_js_error_count"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>live_core.struggle_indicator_js_error_count.idpage</code>.
     */
    public final TableField<StruggleIndicatorJsErrorCountRecord, BigDecimal> IDPAGE = createField(DSL.name("idpage"), SQLDataType.NUMERIC, this, "");

    /**
     * The column
     * <code>live_core.struggle_indicator_js_error_count.value</code>.
     */
    public final TableField<StruggleIndicatorJsErrorCountRecord, Long> VALUE = createField(DSL.name("value"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>live_core.struggle_indicator_js_error_count.relative_time</code>.
     */
    public final TableField<StruggleIndicatorJsErrorCountRecord, Long> RELATIVE_TIME = createField(DSL.name("relative_time"), SQLDataType.BIGINT, this, "");

    private StruggleIndicatorJsErrorCount(Name alias, Table<StruggleIndicatorJsErrorCountRecord> aliased) {
        this(alias, aliased, null);
    }

    private StruggleIndicatorJsErrorCount(Name alias, Table<StruggleIndicatorJsErrorCountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Easy access to underlying table in other schemas."), TableOptions.view("create view \"struggle_indicator_js_error_count\" as  SELECT struggle_indicator_js_error_count.idstruggle_indicator_js_error_count,\n    struggle_indicator_js_error_count.idpage,\n    struggle_indicator_js_error_count.value,\n    struggle_indicator_js_error_count.relative_time\n   FROM live.struggle_indicator_js_error_count;"));
    }

    /**
     * Create an aliased
     * <code>live_core.struggle_indicator_js_error_count</code> table reference
     */
    public StruggleIndicatorJsErrorCount(String alias) {
        this(DSL.name(alias), STRUGGLE_INDICATOR_JS_ERROR_COUNT);
    }

    /**
     * Create an aliased
     * <code>live_core.struggle_indicator_js_error_count</code> table reference
     */
    public StruggleIndicatorJsErrorCount(Name alias) {
        this(alias, STRUGGLE_INDICATOR_JS_ERROR_COUNT);
    }

    /**
     * Create a <code>live_core.struggle_indicator_js_error_count</code> table
     * reference
     */
    public StruggleIndicatorJsErrorCount() {
        this(DSL.name("struggle_indicator_js_error_count"), null);
    }

    public <O extends Record> StruggleIndicatorJsErrorCount(Table<O> child, ForeignKey<O, StruggleIndicatorJsErrorCountRecord> key) {
        super(child, key, STRUGGLE_INDICATOR_JS_ERROR_COUNT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : LiveCore.LIVE_CORE;
    }

    @Override
    public StruggleIndicatorJsErrorCount as(String alias) {
        return new StruggleIndicatorJsErrorCount(DSL.name(alias), this);
    }

    @Override
    public StruggleIndicatorJsErrorCount as(Name alias) {
        return new StruggleIndicatorJsErrorCount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StruggleIndicatorJsErrorCount rename(String name) {
        return new StruggleIndicatorJsErrorCount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StruggleIndicatorJsErrorCount rename(Name name) {
        return new StruggleIndicatorJsErrorCount(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, BigDecimal, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
