/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables.records;


import com.verint.mpathy.db.live_core.tables.BucketCountZdth64uzum;

import java.math.BigDecimal;
import java.time.LocalTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BucketCountZdth64uzumRecord extends TableRecordImpl<BucketCountZdth64uzumRecord> implements Record4<Integer, BigDecimal, LocalTime, LocalTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live_core.bucket_count_ZDTH64uZUM.idsite</code>.
     */
    public void setIdsite(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>live_core.bucket_count_ZDTH64uZUM.idsite</code>.
     */
    public Integer getIdsite() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>live_core.bucket_count_ZDTH64uZUM.idbucket</code>.
     */
    public void setIdbucket(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>live_core.bucket_count_ZDTH64uZUM.idbucket</code>.
     */
    public BigDecimal getIdbucket() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>live_core.bucket_count_ZDTH64uZUM.start_date</code>.
     */
    public void setStartDate(LocalTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>live_core.bucket_count_ZDTH64uZUM.start_date</code>.
     */
    public LocalTime getStartDate() {
        return (LocalTime) get(2);
    }

    /**
     * Setter for <code>live_core.bucket_count_ZDTH64uZUM.stop_date</code>.
     */
    public void setStopDate(LocalTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>live_core.bucket_count_ZDTH64uZUM.stop_date</code>.
     */
    public LocalTime getStopDate() {
        return (LocalTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, BigDecimal, LocalTime, LocalTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, BigDecimal, LocalTime, LocalTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM.IDSITE;
    }

    @Override
    public Field<BigDecimal> field2() {
        return BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM.IDBUCKET;
    }

    @Override
    public Field<LocalTime> field3() {
        return BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM.START_DATE;
    }

    @Override
    public Field<LocalTime> field4() {
        return BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM.STOP_DATE;
    }

    @Override
    public Integer component1() {
        return getIdsite();
    }

    @Override
    public BigDecimal component2() {
        return getIdbucket();
    }

    @Override
    public LocalTime component3() {
        return getStartDate();
    }

    @Override
    public LocalTime component4() {
        return getStopDate();
    }

    @Override
    public Integer value1() {
        return getIdsite();
    }

    @Override
    public BigDecimal value2() {
        return getIdbucket();
    }

    @Override
    public LocalTime value3() {
        return getStartDate();
    }

    @Override
    public LocalTime value4() {
        return getStopDate();
    }

    @Override
    public BucketCountZdth64uzumRecord value1(Integer value) {
        setIdsite(value);
        return this;
    }

    @Override
    public BucketCountZdth64uzumRecord value2(BigDecimal value) {
        setIdbucket(value);
        return this;
    }

    @Override
    public BucketCountZdth64uzumRecord value3(LocalTime value) {
        setStartDate(value);
        return this;
    }

    @Override
    public BucketCountZdth64uzumRecord value4(LocalTime value) {
        setStopDate(value);
        return this;
    }

    @Override
    public BucketCountZdth64uzumRecord values(Integer value1, BigDecimal value2, LocalTime value3, LocalTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BucketCountZdth64uzumRecord
     */
    public BucketCountZdth64uzumRecord() {
        super(BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM);
    }

    /**
     * Create a detached, initialised BucketCountZdth64uzumRecord
     */
    public BucketCountZdth64uzumRecord(Integer idsite, BigDecimal idbucket, LocalTime startDate, LocalTime stopDate) {
        super(BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM);

        setIdsite(idsite);
        setIdbucket(idbucket);
        setStartDate(startDate);
        setStopDate(stopDate);
    }
}
