/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core.tables.records;


import com.verint.mpathy.db.live_core.tables.StruggleScorePage;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * Easy access to underlying table in other schemas.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StruggleScorePageRecord extends TableRecordImpl<StruggleScorePageRecord> implements Record5<Long, Integer, BigDecimal, BigDecimal, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>live_core.struggle_score_page.idstruggle_score_page</code>.
     */
    public void setIdstruggleScorePage(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>live_core.struggle_score_page.idstruggle_score_page</code>.
     */
    public Long getIdstruggleScorePage() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>live_core.struggle_score_page.idsite</code>.
     */
    public void setIdsite(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>live_core.struggle_score_page.idsite</code>.
     */
    public Integer getIdsite() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>live_core.struggle_score_page.idsession</code>.
     */
    public void setIdsession(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>live_core.struggle_score_page.idsession</code>.
     */
    public BigDecimal getIdsession() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>live_core.struggle_score_page.idpage</code>.
     */
    public void setIdpage(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>live_core.struggle_score_page.idpage</code>.
     */
    public BigDecimal getIdpage() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>live_core.struggle_score_page.score</code>.
     */
    public void setScore(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>live_core.struggle_score_page.score</code>.
     */
    public Long getScore() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Integer, BigDecimal, BigDecimal, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Integer, BigDecimal, BigDecimal, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return StruggleScorePage.STRUGGLE_SCORE_PAGE.IDSTRUGGLE_SCORE_PAGE;
    }

    @Override
    public Field<Integer> field2() {
        return StruggleScorePage.STRUGGLE_SCORE_PAGE.IDSITE;
    }

    @Override
    public Field<BigDecimal> field3() {
        return StruggleScorePage.STRUGGLE_SCORE_PAGE.IDSESSION;
    }

    @Override
    public Field<BigDecimal> field4() {
        return StruggleScorePage.STRUGGLE_SCORE_PAGE.IDPAGE;
    }

    @Override
    public Field<Long> field5() {
        return StruggleScorePage.STRUGGLE_SCORE_PAGE.SCORE;
    }

    @Override
    public Long component1() {
        return getIdstruggleScorePage();
    }

    @Override
    public Integer component2() {
        return getIdsite();
    }

    @Override
    public BigDecimal component3() {
        return getIdsession();
    }

    @Override
    public BigDecimal component4() {
        return getIdpage();
    }

    @Override
    public Long component5() {
        return getScore();
    }

    @Override
    public Long value1() {
        return getIdstruggleScorePage();
    }

    @Override
    public Integer value2() {
        return getIdsite();
    }

    @Override
    public BigDecimal value3() {
        return getIdsession();
    }

    @Override
    public BigDecimal value4() {
        return getIdpage();
    }

    @Override
    public Long value5() {
        return getScore();
    }

    @Override
    public StruggleScorePageRecord value1(Long value) {
        setIdstruggleScorePage(value);
        return this;
    }

    @Override
    public StruggleScorePageRecord value2(Integer value) {
        setIdsite(value);
        return this;
    }

    @Override
    public StruggleScorePageRecord value3(BigDecimal value) {
        setIdsession(value);
        return this;
    }

    @Override
    public StruggleScorePageRecord value4(BigDecimal value) {
        setIdpage(value);
        return this;
    }

    @Override
    public StruggleScorePageRecord value5(Long value) {
        setScore(value);
        return this;
    }

    @Override
    public StruggleScorePageRecord values(Long value1, Integer value2, BigDecimal value3, BigDecimal value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StruggleScorePageRecord
     */
    public StruggleScorePageRecord() {
        super(StruggleScorePage.STRUGGLE_SCORE_PAGE);
    }

    /**
     * Create a detached, initialised StruggleScorePageRecord
     */
    public StruggleScorePageRecord(Long idstruggleScorePage, Integer idsite, BigDecimal idsession, BigDecimal idpage, Long score) {
        super(StruggleScorePage.STRUGGLE_SCORE_PAGE);

        setIdstruggleScorePage(idstruggleScorePage);
        setIdsite(idsite);
        setIdsession(idsession);
        setIdpage(idpage);
        setScore(score);
    }
}
