/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live_core;


import com.verint.mpathy.db.DefaultCatalog;
import com.verint.mpathy.db.live_core.tables.Account;
import com.verint.mpathy.db.live_core.tables.AdobeAnalyticsFilter;
import com.verint.mpathy.db.live_core.tables.AdobeAnalyticsFilterSession;
import com.verint.mpathy.db.live_core.tables.AdobeAnalyticsFilterVisitor;
import com.verint.mpathy.db.live_core.tables.AdobeAnalyticsSuite;
import com.verint.mpathy.db.live_core.tables.AdobeAnalyticsSuiteImportsettings;
import com.verint.mpathy.db.live_core.tables.AggregationPlan;
import com.verint.mpathy.db.live_core.tables.Bucket;
import com.verint.mpathy.db.live_core.tables.BucketAlertEmailSetting;
import com.verint.mpathy.db.live_core.tables.BucketCount;
import com.verint.mpathy.db.live_core.tables.BucketCountBase;
import com.verint.mpathy.db.live_core.tables.BucketCountBdtcjn6dtf;
import com.verint.mpathy.db.live_core.tables.BucketCountCwav87wdqu;
import com.verint.mpathy.db.live_core.tables.BucketCountMdxdlwkdtm;
import com.verint.mpathy.db.live_core.tables.BucketCountVuxuvm8wek;
import com.verint.mpathy.db.live_core.tables.BucketCountXwwlf8vbaw;
import com.verint.mpathy.db.live_core.tables.BucketCountZdth64uzum;
import com.verint.mpathy.db.live_core.tables.BucketTemplate;
import com.verint.mpathy.db.live_core.tables.CassandraCleanlist;
import com.verint.mpathy.db.live_core.tables.ComscoreFilter;
import com.verint.mpathy.db.live_core.tables.ComscoreFilterPids;
import com.verint.mpathy.db.live_core.tables.CpCount_10001Pageimpression;
import com.verint.mpathy.db.live_core.tables.CpCount_1Pageimpression;
import com.verint.mpathy.db.live_core.tables.CpCount_1Session;
import com.verint.mpathy.db.live_core.tables.CpCount_2Pageimpression;
import com.verint.mpathy.db.live_core.tables.CpCount_3Pageimpression;
import com.verint.mpathy.db.live_core.tables.CpCount_3Session;
import com.verint.mpathy.db.live_core.tables.CpCount_4Pageimpression;
import com.verint.mpathy.db.live_core.tables.CpCount_5Pageimpression;
import com.verint.mpathy.db.live_core.tables.CpCount_5Session;
import com.verint.mpathy.db.live_core.tables.Cp_10001Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_10010Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_1Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_1Session;
import com.verint.mpathy.db.live_core.tables.Cp_2Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_3338Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_3338Session;
import com.verint.mpathy.db.live_core.tables.Cp_3Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_3Session;
import com.verint.mpathy.db.live_core.tables.Cp_4Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_5Pageimpression;
import com.verint.mpathy.db.live_core.tables.Cp_5Session;
import com.verint.mpathy.db.live_core.tables.Customparameter;
import com.verint.mpathy.db.live_core.tables.CustomparameterDomtree;
import com.verint.mpathy.db.live_core.tables.CustomparameterLucene;
import com.verint.mpathy.db.live_core.tables.CustomparameterPatterndetector;
import com.verint.mpathy.db.live_core.tables.CustomparameterSqlquery;
import com.verint.mpathy.db.live_core.tables.DataBaseTest;
import com.verint.mpathy.db.live_core.tables.DebugClient;
import com.verint.mpathy.db.live_core.tables.DeviceInfoJsonPair;
import com.verint.mpathy.db.live_core.tables.Document;
import com.verint.mpathy.db.live_core.tables.Element;
import com.verint.mpathy.db.live_core.tables.ElementVisible;
import com.verint.mpathy.db.live_core.tables.Event;
import com.verint.mpathy.db.live_core.tables.EventClick;
import com.verint.mpathy.db.live_core.tables.EventFocus;
import com.verint.mpathy.db.live_core.tables.EventHover;
import com.verint.mpathy.db.live_core.tables.EventTable;
import com.verint.mpathy.db.live_core.tables.ExceptionFilter;
import com.verint.mpathy.db.live_core.tables.Exportqueue;
import com.verint.mpathy.db.live_core.tables.FormelementAction;
import com.verint.mpathy.db.live_core.tables.FormelementactionHasTaskitem;
import com.verint.mpathy.db.live_core.tables.Gesture;
import com.verint.mpathy.db.live_core.tables.HeadlessAnswer;
import com.verint.mpathy.db.live_core.tables.HeadlessPollsShowed;
import com.verint.mpathy.db.live_core.tables.HeadlessResponseRate;
import com.verint.mpathy.db.live_core.tables.HeadlessanswerHasProperty;
import com.verint.mpathy.db.live_core.tables.HistoryTrackingAmount;
import com.verint.mpathy.db.live_core.tables.HistoryTrackingRate;
import com.verint.mpathy.db.live_core.tables.Is24Filter;
import com.verint.mpathy.db.live_core.tables.Is24FilterPids;
import com.verint.mpathy.db.live_core.tables.JsonDatatype;
import com.verint.mpathy.db.live_core.tables.JsonKey;
import com.verint.mpathy.db.live_core.tables.JsonValue;
import com.verint.mpathy.db.live_core.tables.LogPageHasAnswer;
import com.verint.mpathy.db.live_core.tables.LogSession;
import com.verint.mpathy.db.live_core.tables.LogSessionState;
import com.verint.mpathy.db.live_core.tables.MagicCode;
import com.verint.mpathy.db.live_core.tables.MapClick;
import com.verint.mpathy.db.live_core.tables.MapClickBotched;
import com.verint.mpathy.db.live_core.tables.MapClickCleanup;
import com.verint.mpathy.db.live_core.tables.MapClickKp;
import com.verint.mpathy.db.live_core.tables.MapClickPathinfo;
import com.verint.mpathy.db.live_core.tables.MapClickPathinfo_11024;
import com.verint.mpathy.db.live_core.tables.MapClickPathinfo_11198;
import com.verint.mpathy.db.live_core.tables.MapClickPathinfo_11689;
import com.verint.mpathy.db.live_core.tables.MapClickPathnode;
import com.verint.mpathy.db.live_core.tables.MapClickSettings;
import com.verint.mpathy.db.live_core.tables.MapClick_3135;
import com.verint.mpathy.db.live_core.tables.MapFocus;
import com.verint.mpathy.db.live_core.tables.MapMove;
import com.verint.mpathy.db.live_core.tables.MapMove_3;
import com.verint.mpathy.db.live_core.tables.MapScroll;
import com.verint.mpathy.db.live_core.tables.MapVisible;
import com.verint.mpathy.db.live_core.tables.Mdata;
import com.verint.mpathy.db.live_core.tables.Metadata;
import com.verint.mpathy.db.live_core.tables.MobileDevice;
import com.verint.mpathy.db.live_core.tables.MobileMetric;
import com.verint.mpathy.db.live_core.tables.Movement_0t1;
import com.verint.mpathy.db.live_core.tables.Movement_10t60;
import com.verint.mpathy.db.live_core.tables.Movement_120;
import com.verint.mpathy.db.live_core.tables.Movement_1t2;
import com.verint.mpathy.db.live_core.tables.Movement_2t3;
import com.verint.mpathy.db.live_core.tables.Movement_3t4;
import com.verint.mpathy.db.live_core.tables.Movement_4t5;
import com.verint.mpathy.db.live_core.tables.Movement_5t10;
import com.verint.mpathy.db.live_core.tables.Movement_60t120;
import com.verint.mpathy.db.live_core.tables.Movementmap;
import com.verint.mpathy.db.live_core.tables.Page;
import com.verint.mpathy.db.live_core.tables.PageFilter;
import com.verint.mpathy.db.live_core.tables.PageHasAnswer;
import com.verint.mpathy.db.live_core.tables.PageHasEtlvisitorreplayreadyevent;
import com.verint.mpathy.db.live_core.tables.PageHasGesture;
import com.verint.mpathy.db.live_core.tables.PageHasResource;
import com.verint.mpathy.db.live_core.tables.PageHasRespondent;
import com.verint.mpathy.db.live_core.tables.PageHasRespondentProd;
import com.verint.mpathy.db.live_core.tables.PageHasRespondentoldVoc_13071;
import com.verint.mpathy.db.live_core.tables.PageHasTag;
import com.verint.mpathy.db.live_core.tables.PageHasVideo;
import com.verint.mpathy.db.live_core.tables.PageName;
import com.verint.mpathy.db.live_core.tables.PageNameBlocklist;
import com.verint.mpathy.db.live_core.tables.PageNameImport;
import com.verint.mpathy.db.live_core.tables.PageStats;
import com.verint.mpathy.db.live_core.tables.PagenamesToDelete;
import com.verint.mpathy.db.live_core.tables.Privilege;
import com.verint.mpathy.db.live_core.tables.PropertyValues;
import com.verint.mpathy.db.live_core.tables.Questionnaire;
import com.verint.mpathy.db.live_core.tables.QuestionnaireAlert;
import com.verint.mpathy.db.live_core.tables.QuestionnaireCrypt;
import com.verint.mpathy.db.live_core.tables.QuestionnaireElement;
import com.verint.mpathy.db.live_core.tables.QuestionnaireHasExport;
import com.verint.mpathy.db.live_core.tables.QuestionnaireHasFile;
import com.verint.mpathy.db.live_core.tables.QuestionnaireLayout;
import com.verint.mpathy.db.live_core.tables.QuestionnaireType;
import com.verint.mpathy.db.live_core.tables.Raster;
import com.verint.mpathy.db.live_core.tables.Ratio;
import com.verint.mpathy.db.live_core.tables.RatioType;
import com.verint.mpathy.db.live_core.tables.ResourceExcludeBot;
import com.verint.mpathy.db.live_core.tables.ResourceExcludeHost;
import com.verint.mpathy.db.live_core.tables.ResourceExcludeKeyword;
import com.verint.mpathy.db.live_core.tables.ResourceHasParent;
import com.verint.mpathy.db.live_core.tables.ResourceIncludeProtocol;
import com.verint.mpathy.db.live_core.tables.ResourceOld;
import com.verint.mpathy.db.live_core.tables.ResourceReimport;
import com.verint.mpathy.db.live_core.tables.ResourceRule;
import com.verint.mpathy.db.live_core.tables.SafHasSegments;
import com.verint.mpathy.db.live_core.tables.SafSegmentHasPage;
import com.verint.mpathy.db.live_core.tables.SchemaInfo;
import com.verint.mpathy.db.live_core.tables.Scrollingmap;
import com.verint.mpathy.db.live_core.tables.Server;
import com.verint.mpathy.db.live_core.tables.Session;
import com.verint.mpathy.db.live_core.tables.SessionHasMetadata;
import com.verint.mpathy.db.live_core.tables.SessionHasMobileDevice;
import com.verint.mpathy.db.live_core.tables.SessionHasPagename;
import com.verint.mpathy.db.live_core.tables.SessionHasResource;
import com.verint.mpathy.db.live_core.tables.SessionReimport;
import com.verint.mpathy.db.live_core.tables.SessionSelection;
import com.verint.mpathy.db.live_core.tables.Sessionstats24h;
import com.verint.mpathy.db.live_core.tables.Settings;
import com.verint.mpathy.db.live_core.tables.Site;
import com.verint.mpathy.db.live_core.tables.SiteApiFiles;
import com.verint.mpathy.db.live_core.tables.SiteHasVendor;
import com.verint.mpathy.db.live_core.tables.Sitestats;
import com.verint.mpathy.db.live_core.tables.StageJsonPair;
import com.verint.mpathy.db.live_core.tables.StoredFilter;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorDeadClickCount;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorDomloadTime;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorErrorMessageCount;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorErrorPage;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorFormFieldAbandonment;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorFormFieldModificationCount;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorFunnelStepRepetition;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorJsErrorCount;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorLongInputTime;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorRageClickCount;
import com.verint.mpathy.db.live_core.tables.StruggleIndicatorScrollDirectionChangeCount;
import com.verint.mpathy.db.live_core.tables.StruggleScorePage;
import com.verint.mpathy.db.live_core.tables.StruggleScoreSession;
import com.verint.mpathy.db.live_core.tables.Tag;
import com.verint.mpathy.db.live_core.tables.Task;
import com.verint.mpathy.db.live_core.tables.TaskAction;
import com.verint.mpathy.db.live_core.tables.TaskHasRatio;
import com.verint.mpathy.db.live_core.tables.TaskItem;
import com.verint.mpathy.db.live_core.tables.TaskItemAction;
import com.verint.mpathy.db.live_core.tables.TaskitemHasPage;
import com.verint.mpathy.db.live_core.tables.TaskitemHasPagename;
import com.verint.mpathy.db.live_core.tables.TestDv_2020_07_24;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20010141;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20013229;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20014116;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20014677;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2001621;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2001646;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20017851;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20018558;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20018769;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_20019106;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_200343;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2005866;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2005981;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2006763;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2007834;
import com.verint.mpathy.db.live_core.tables.TmpForDebugDeleteSessions_2009120;
import com.verint.mpathy.db.live_core.tables.TmpSelection_266184216;
import com.verint.mpathy.db.live_core.tables.TmpSelection_63943770;
import com.verint.mpathy.db.live_core.tables.Tmp_0;
import com.verint.mpathy.db.live_core.tables.TrackingConfig;
import com.verint.mpathy.db.live_core.tables.TrackingSetup;
import com.verint.mpathy.db.live_core.tables.Trafficstats;
import com.verint.mpathy.db.live_core.tables.Trafficstats31d;
import com.verint.mpathy.db.live_core.tables.UnmappedPage;
import com.verint.mpathy.db.live_core.tables.Url;
import com.verint.mpathy.db.live_core.tables.User;
import com.verint.mpathy.db.live_core.tables.UserFingerprint;
import com.verint.mpathy.db.live_core.tables.UserHasPrivilege;
import com.verint.mpathy.db.live_core.tables.UserHasSaf;
import com.verint.mpathy.db.live_core.tables.UserHasSite;
import com.verint.mpathy.db.live_core.tables.UserViewedDashboard;
import com.verint.mpathy.db.live_core.tables.Useragent;
import com.verint.mpathy.db.live_core.tables.Useragents2;
import com.verint.mpathy.db.live_core.tables.Useragents3;
import com.verint.mpathy.db.live_core.tables.Vendor;
import com.verint.mpathy.db.live_core.tables.Video;
import com.verint.mpathy.db.live_core.tables.VideoPageStats;
import com.verint.mpathy.db.live_core.tables.Visitor;
import com.verint.mpathy.db.live_core.tables._SessionSelection;
import com.verint.mpathy.db.live_core.tables._TmpUseragentsDv2020_08_06;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveCore extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live_core</code>
     */
    public static final LiveCore LIVE_CORE = new LiveCore();

    /**
     * Easy access to underlying table in other schemas.
     */
    public final _SessionSelection _SESSION_SELECTION = _SessionSelection._SESSION_SELECTION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final _TmpUseragentsDv2020_08_06 _TMP_USERAGENTS_DV2020_08_06 = _TmpUseragentsDv2020_08_06._TMP_USERAGENTS_DV2020_08_06;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final AdobeAnalyticsFilter ADOBE_ANALYTICS_FILTER = AdobeAnalyticsFilter.ADOBE_ANALYTICS_FILTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final AdobeAnalyticsFilterSession ADOBE_ANALYTICS_FILTER_SESSION = AdobeAnalyticsFilterSession.ADOBE_ANALYTICS_FILTER_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final AdobeAnalyticsFilterVisitor ADOBE_ANALYTICS_FILTER_VISITOR = AdobeAnalyticsFilterVisitor.ADOBE_ANALYTICS_FILTER_VISITOR;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final AdobeAnalyticsSuite ADOBE_ANALYTICS_SUITE = AdobeAnalyticsSuite.ADOBE_ANALYTICS_SUITE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final AdobeAnalyticsSuiteImportsettings ADOBE_ANALYTICS_SUITE_IMPORTSETTINGS = AdobeAnalyticsSuiteImportsettings.ADOBE_ANALYTICS_SUITE_IMPORTSETTINGS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final AggregationPlan AGGREGATION_PLAN = AggregationPlan.AGGREGATION_PLAN;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Bucket BUCKET = Bucket.BUCKET;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketAlertEmailSetting BUCKET_ALERT_EMAIL_SETTING = BucketAlertEmailSetting.BUCKET_ALERT_EMAIL_SETTING;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCount BUCKET_COUNT = BucketCount.BUCKET_COUNT;

    /**
     * The table <code>live_core.bucket_count_base</code>.
     */
    public final BucketCountBase BUCKET_COUNT_BASE = BucketCountBase.BUCKET_COUNT_BASE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCountBdtcjn6dtf BUCKET_COUNT_BDTCJN6DTF = BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCountCwav87wdqu BUCKET_COUNT_CWAV87WDQU = BucketCountCwav87wdqu.BUCKET_COUNT_CWAV87WDQU;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCountMdxdlwkdtm BUCKET_COUNT_MDXDLWKDTM = BucketCountMdxdlwkdtm.BUCKET_COUNT_MDXDLWKDTM;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCountVuxuvm8wek BUCKET_COUNT_VUXUVM8WEK = BucketCountVuxuvm8wek.BUCKET_COUNT_VUXUVM8WEK;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCountXwwlf8vbaw BUCKET_COUNT_XWWLF8VBAW = BucketCountXwwlf8vbaw.BUCKET_COUNT_XWWLF8VBAW;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketCountZdth64uzum BUCKET_COUNT_ZDTH64UZUM = BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final BucketTemplate BUCKET_TEMPLATE = BucketTemplate.BUCKET_TEMPLATE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final CassandraCleanlist CASSANDRA_CLEANLIST = CassandraCleanlist.CASSANDRA_CLEANLIST;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ComscoreFilter COMSCORE_FILTER = ComscoreFilter.COMSCORE_FILTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ComscoreFilterPids COMSCORE_FILTER_PIDS = ComscoreFilterPids.COMSCORE_FILTER_PIDS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_10001Pageimpression CP_10001_PAGEIMPRESSION = Cp_10001Pageimpression.CP_10001_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_10010Pageimpression CP_10010_PAGEIMPRESSION = Cp_10010Pageimpression.CP_10010_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_1Pageimpression CP_1_PAGEIMPRESSION = Cp_1Pageimpression.CP_1_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_1Session CP_1_SESSION = Cp_1Session.CP_1_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_2Pageimpression CP_2_PAGEIMPRESSION = Cp_2Pageimpression.CP_2_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_3338Pageimpression CP_3338_PAGEIMPRESSION = Cp_3338Pageimpression.CP_3338_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_3338Session CP_3338_SESSION = Cp_3338Session.CP_3338_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_3Pageimpression CP_3_PAGEIMPRESSION = Cp_3Pageimpression.CP_3_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_3Session CP_3_SESSION = Cp_3Session.CP_3_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_4Pageimpression CP_4_PAGEIMPRESSION = Cp_4Pageimpression.CP_4_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_5Pageimpression CP_5_PAGEIMPRESSION = Cp_5Pageimpression.CP_5_PAGEIMPRESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Cp_5Session CP_5_SESSION = Cp_5Session.CP_5_SESSION;

    /**
     * The table <code>live_core.cp_count_10001_pageimpression</code>.
     */
    public final CpCount_10001Pageimpression CP_COUNT_10001_PAGEIMPRESSION = CpCount_10001Pageimpression.CP_COUNT_10001_PAGEIMPRESSION;

    /**
     * The table <code>live_core.cp_count_1_pageimpression</code>.
     */
    public final CpCount_1Pageimpression CP_COUNT_1_PAGEIMPRESSION = CpCount_1Pageimpression.CP_COUNT_1_PAGEIMPRESSION;

    /**
     * The table <code>live_core.cp_count_1_session</code>.
     */
    public final CpCount_1Session CP_COUNT_1_SESSION = CpCount_1Session.CP_COUNT_1_SESSION;

    /**
     * The table <code>live_core.cp_count_2_pageimpression</code>.
     */
    public final CpCount_2Pageimpression CP_COUNT_2_PAGEIMPRESSION = CpCount_2Pageimpression.CP_COUNT_2_PAGEIMPRESSION;

    /**
     * The table <code>live_core.cp_count_3_pageimpression</code>.
     */
    public final CpCount_3Pageimpression CP_COUNT_3_PAGEIMPRESSION = CpCount_3Pageimpression.CP_COUNT_3_PAGEIMPRESSION;

    /**
     * The table <code>live_core.cp_count_3_session</code>.
     */
    public final CpCount_3Session CP_COUNT_3_SESSION = CpCount_3Session.CP_COUNT_3_SESSION;

    /**
     * The table <code>live_core.cp_count_4_pageimpression</code>.
     */
    public final CpCount_4Pageimpression CP_COUNT_4_PAGEIMPRESSION = CpCount_4Pageimpression.CP_COUNT_4_PAGEIMPRESSION;

    /**
     * The table <code>live_core.cp_count_5_pageimpression</code>.
     */
    public final CpCount_5Pageimpression CP_COUNT_5_PAGEIMPRESSION = CpCount_5Pageimpression.CP_COUNT_5_PAGEIMPRESSION;

    /**
     * The table <code>live_core.cp_count_5_session</code>.
     */
    public final CpCount_5Session CP_COUNT_5_SESSION = CpCount_5Session.CP_COUNT_5_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Customparameter CUSTOMPARAMETER = Customparameter.CUSTOMPARAMETER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final CustomparameterDomtree CUSTOMPARAMETER_DOMTREE = CustomparameterDomtree.CUSTOMPARAMETER_DOMTREE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final CustomparameterLucene CUSTOMPARAMETER_LUCENE = CustomparameterLucene.CUSTOMPARAMETER_LUCENE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final CustomparameterPatterndetector CUSTOMPARAMETER_PATTERNDETECTOR = CustomparameterPatterndetector.CUSTOMPARAMETER_PATTERNDETECTOR;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final CustomparameterSqlquery CUSTOMPARAMETER_SQLQUERY = CustomparameterSqlquery.CUSTOMPARAMETER_SQLQUERY;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final DataBaseTest DATA_BASE_TEST = DataBaseTest.DATA_BASE_TEST;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final DebugClient DEBUG_CLIENT = DebugClient.DEBUG_CLIENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final DeviceInfoJsonPair DEVICE_INFO_JSON_PAIR = DeviceInfoJsonPair.DEVICE_INFO_JSON_PAIR;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Document DOCUMENT = Document.DOCUMENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Element ELEMENT = Element.ELEMENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ElementVisible ELEMENT_VISIBLE = ElementVisible.ELEMENT_VISIBLE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final EventClick EVENT_CLICK = EventClick.EVENT_CLICK;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final EventFocus EVENT_FOCUS = EventFocus.EVENT_FOCUS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final EventHover EVENT_HOVER = EventHover.EVENT_HOVER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final EventTable EVENT_TABLE = EventTable.EVENT_TABLE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ExceptionFilter EXCEPTION_FILTER = ExceptionFilter.EXCEPTION_FILTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Exportqueue EXPORTQUEUE = Exportqueue.EXPORTQUEUE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final FormelementAction FORMELEMENT_ACTION = FormelementAction.FORMELEMENT_ACTION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final FormelementactionHasTaskitem FORMELEMENTACTION_HAS_TASKITEM = FormelementactionHasTaskitem.FORMELEMENTACTION_HAS_TASKITEM;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Gesture GESTURE = Gesture.GESTURE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final HeadlessAnswer HEADLESS_ANSWER = HeadlessAnswer.HEADLESS_ANSWER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final HeadlessPollsShowed HEADLESS_POLLS_SHOWED = HeadlessPollsShowed.HEADLESS_POLLS_SHOWED;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final HeadlessResponseRate HEADLESS_RESPONSE_RATE = HeadlessResponseRate.HEADLESS_RESPONSE_RATE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final HeadlessanswerHasProperty HEADLESSANSWER_HAS_PROPERTY = HeadlessanswerHasProperty.HEADLESSANSWER_HAS_PROPERTY;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final HistoryTrackingAmount HISTORY_TRACKING_AMOUNT = HistoryTrackingAmount.HISTORY_TRACKING_AMOUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final HistoryTrackingRate HISTORY_TRACKING_RATE = HistoryTrackingRate.HISTORY_TRACKING_RATE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Is24Filter IS24_FILTER = Is24Filter.IS24_FILTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Is24FilterPids IS24_FILTER_PIDS = Is24FilterPids.IS24_FILTER_PIDS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final JsonDatatype JSON_DATATYPE = JsonDatatype.JSON_DATATYPE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final JsonKey JSON_KEY = JsonKey.JSON_KEY;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final JsonValue JSON_VALUE = JsonValue.JSON_VALUE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final LogPageHasAnswer LOG_PAGE_HAS_ANSWER = LogPageHasAnswer.LOG_PAGE_HAS_ANSWER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final LogSession LOG_SESSION = LogSession.LOG_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final LogSessionState LOG_SESSION_STATE = LogSessionState.LOG_SESSION_STATE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MagicCode MAGIC_CODE = MagicCode.MAGIC_CODE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClick MAP_CLICK = MapClick.MAP_CLICK;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClick_3135 MAP_CLICK_3135 = MapClick_3135.MAP_CLICK_3135;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickBotched MAP_CLICK_BOTCHED = MapClickBotched.MAP_CLICK_BOTCHED;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickCleanup MAP_CLICK_CLEANUP = MapClickCleanup.MAP_CLICK_CLEANUP;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickKp MAP_CLICK_KP = MapClickKp.MAP_CLICK_KP;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickPathinfo MAP_CLICK_PATHINFO = MapClickPathinfo.MAP_CLICK_PATHINFO;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickPathinfo_11024 MAP_CLICK_PATHINFO_11024 = MapClickPathinfo_11024.MAP_CLICK_PATHINFO_11024;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickPathinfo_11198 MAP_CLICK_PATHINFO_11198 = MapClickPathinfo_11198.MAP_CLICK_PATHINFO_11198;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickPathinfo_11689 MAP_CLICK_PATHINFO_11689 = MapClickPathinfo_11689.MAP_CLICK_PATHINFO_11689;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickPathnode MAP_CLICK_PATHNODE = MapClickPathnode.MAP_CLICK_PATHNODE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapClickSettings MAP_CLICK_SETTINGS = MapClickSettings.MAP_CLICK_SETTINGS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapFocus MAP_FOCUS = MapFocus.MAP_FOCUS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapMove MAP_MOVE = MapMove.MAP_MOVE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapMove_3 MAP_MOVE_3 = MapMove_3.MAP_MOVE_3;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapScroll MAP_SCROLL = MapScroll.MAP_SCROLL;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MapVisible MAP_VISIBLE = MapVisible.MAP_VISIBLE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Mdata MDATA = Mdata.MDATA;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Metadata METADATA = Metadata.METADATA;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MobileDevice MOBILE_DEVICE = MobileDevice.MOBILE_DEVICE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final MobileMetric MOBILE_METRIC = MobileMetric.MOBILE_METRIC;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_0t1 MOVEMENT_0T1 = Movement_0t1.MOVEMENT_0T1;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_10t60 MOVEMENT_10T60 = Movement_10t60.MOVEMENT_10T60;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_120 MOVEMENT_120 = Movement_120.MOVEMENT_120;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_1t2 MOVEMENT_1T2 = Movement_1t2.MOVEMENT_1T2;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_2t3 MOVEMENT_2T3 = Movement_2t3.MOVEMENT_2T3;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_3t4 MOVEMENT_3T4 = Movement_3t4.MOVEMENT_3T4;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_4t5 MOVEMENT_4T5 = Movement_4t5.MOVEMENT_4T5;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_5t10 MOVEMENT_5T10 = Movement_5t10.MOVEMENT_5T10;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movement_60t120 MOVEMENT_60T120 = Movement_60t120.MOVEMENT_60T120;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Movementmap MOVEMENTMAP = Movementmap.MOVEMENTMAP;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Page PAGE = Page.PAGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageFilter PAGE_FILTER = PageFilter.PAGE_FILTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasAnswer PAGE_HAS_ANSWER = PageHasAnswer.PAGE_HAS_ANSWER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasEtlvisitorreplayreadyevent PAGE_HAS_ETLVISITORREPLAYREADYEVENT = PageHasEtlvisitorreplayreadyevent.PAGE_HAS_ETLVISITORREPLAYREADYEVENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasGesture PAGE_HAS_GESTURE = PageHasGesture.PAGE_HAS_GESTURE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasResource PAGE_HAS_RESOURCE = PageHasResource.PAGE_HAS_RESOURCE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasRespondent PAGE_HAS_RESPONDENT = PageHasRespondent.PAGE_HAS_RESPONDENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasRespondentProd PAGE_HAS_RESPONDENT_PROD = PageHasRespondentProd.PAGE_HAS_RESPONDENT_PROD;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasRespondentoldVoc_13071 PAGE_HAS_RESPONDENTOLD_VOC_13071 = PageHasRespondentoldVoc_13071.PAGE_HAS_RESPONDENTOLD_VOC_13071;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasTag PAGE_HAS_TAG = PageHasTag.PAGE_HAS_TAG;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageHasVideo PAGE_HAS_VIDEO = PageHasVideo.PAGE_HAS_VIDEO;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageName PAGE_NAME = PageName.PAGE_NAME;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageNameBlocklist PAGE_NAME_BLOCKLIST = PageNameBlocklist.PAGE_NAME_BLOCKLIST;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageNameImport PAGE_NAME_IMPORT = PageNameImport.PAGE_NAME_IMPORT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PageStats PAGE_STATS = PageStats.PAGE_STATS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PagenamesToDelete PAGENAMES_TO_DELETE = PagenamesToDelete.PAGENAMES_TO_DELETE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Privilege PRIVILEGE = Privilege.PRIVILEGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final PropertyValues PROPERTY_VALUES = PropertyValues.PROPERTY_VALUES;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Questionnaire QUESTIONNAIRE = Questionnaire.QUESTIONNAIRE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireAlert QUESTIONNAIRE_ALERT = QuestionnaireAlert.QUESTIONNAIRE_ALERT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireCrypt QUESTIONNAIRE_CRYPT = QuestionnaireCrypt.QUESTIONNAIRE_CRYPT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireElement QUESTIONNAIRE_ELEMENT = QuestionnaireElement.QUESTIONNAIRE_ELEMENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireHasExport QUESTIONNAIRE_HAS_EXPORT = QuestionnaireHasExport.QUESTIONNAIRE_HAS_EXPORT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireHasFile QUESTIONNAIRE_HAS_FILE = QuestionnaireHasFile.QUESTIONNAIRE_HAS_FILE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireLayout QUESTIONNAIRE_LAYOUT = QuestionnaireLayout.QUESTIONNAIRE_LAYOUT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final QuestionnaireType QUESTIONNAIRE_TYPE = QuestionnaireType.QUESTIONNAIRE_TYPE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Raster RASTER = Raster.RASTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Ratio RATIO = Ratio.RATIO;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final RatioType RATIO_TYPE = RatioType.RATIO_TYPE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceExcludeBot RESOURCE_EXCLUDE_BOT = ResourceExcludeBot.RESOURCE_EXCLUDE_BOT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceExcludeHost RESOURCE_EXCLUDE_HOST = ResourceExcludeHost.RESOURCE_EXCLUDE_HOST;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceExcludeKeyword RESOURCE_EXCLUDE_KEYWORD = ResourceExcludeKeyword.RESOURCE_EXCLUDE_KEYWORD;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceHasParent RESOURCE_HAS_PARENT = ResourceHasParent.RESOURCE_HAS_PARENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceIncludeProtocol RESOURCE_INCLUDE_PROTOCOL = ResourceIncludeProtocol.RESOURCE_INCLUDE_PROTOCOL;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceOld RESOURCE_OLD = ResourceOld.RESOURCE_OLD;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceReimport RESOURCE_REIMPORT = ResourceReimport.RESOURCE_REIMPORT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final ResourceRule RESOURCE_RULE = ResourceRule.RESOURCE_RULE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SafHasSegments SAF_HAS_SEGMENTS = SafHasSegments.SAF_HAS_SEGMENTS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SafSegmentHasPage SAF_SEGMENT_HAS_PAGE = SafSegmentHasPage.SAF_SEGMENT_HAS_PAGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SchemaInfo SCHEMA_INFO = SchemaInfo.SCHEMA_INFO;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Scrollingmap SCROLLINGMAP = Scrollingmap.SCROLLINGMAP;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Server SERVER = Server.SERVER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Session SESSION = Session.SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SessionHasMetadata SESSION_HAS_METADATA = SessionHasMetadata.SESSION_HAS_METADATA;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SessionHasMobileDevice SESSION_HAS_MOBILE_DEVICE = SessionHasMobileDevice.SESSION_HAS_MOBILE_DEVICE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SessionHasPagename SESSION_HAS_PAGENAME = SessionHasPagename.SESSION_HAS_PAGENAME;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SessionHasResource SESSION_HAS_RESOURCE = SessionHasResource.SESSION_HAS_RESOURCE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SessionReimport SESSION_REIMPORT = SessionReimport.SESSION_REIMPORT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SessionSelection SESSION_SELECTION = SessionSelection.SESSION_SELECTION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Sessionstats24h SESSIONSTATS24H = Sessionstats24h.SESSIONSTATS24H;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Settings SETTINGS = Settings.SETTINGS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Site SITE = Site.SITE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SiteApiFiles SITE_API_FILES = SiteApiFiles.SITE_API_FILES;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final SiteHasVendor SITE_HAS_VENDOR = SiteHasVendor.SITE_HAS_VENDOR;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Sitestats SITESTATS = Sitestats.SITESTATS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StageJsonPair STAGE_JSON_PAIR = StageJsonPair.STAGE_JSON_PAIR;

    /**
     * The table <code>live_core.stored_filter</code>.
     */
    public final StoredFilter STORED_FILTER = StoredFilter.STORED_FILTER;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorDeadClickCount STRUGGLE_INDICATOR_DEAD_CLICK_COUNT = StruggleIndicatorDeadClickCount.STRUGGLE_INDICATOR_DEAD_CLICK_COUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorDomloadTime STRUGGLE_INDICATOR_DOMLOAD_TIME = StruggleIndicatorDomloadTime.STRUGGLE_INDICATOR_DOMLOAD_TIME;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorErrorMessageCount STRUGGLE_INDICATOR_ERROR_MESSAGE_COUNT = StruggleIndicatorErrorMessageCount.STRUGGLE_INDICATOR_ERROR_MESSAGE_COUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorErrorPage STRUGGLE_INDICATOR_ERROR_PAGE = StruggleIndicatorErrorPage.STRUGGLE_INDICATOR_ERROR_PAGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorFormFieldAbandonment STRUGGLE_INDICATOR_FORM_FIELD_ABANDONMENT = StruggleIndicatorFormFieldAbandonment.STRUGGLE_INDICATOR_FORM_FIELD_ABANDONMENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorFormFieldModificationCount STRUGGLE_INDICATOR_FORM_FIELD_MODIFICATION_COUNT = StruggleIndicatorFormFieldModificationCount.STRUGGLE_INDICATOR_FORM_FIELD_MODIFICATION_COUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorFunnelStepRepetition STRUGGLE_INDICATOR_FUNNEL_STEP_REPETITION = StruggleIndicatorFunnelStepRepetition.STRUGGLE_INDICATOR_FUNNEL_STEP_REPETITION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorJsErrorCount STRUGGLE_INDICATOR_JS_ERROR_COUNT = StruggleIndicatorJsErrorCount.STRUGGLE_INDICATOR_JS_ERROR_COUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorLongInputTime STRUGGLE_INDICATOR_LONG_INPUT_TIME = StruggleIndicatorLongInputTime.STRUGGLE_INDICATOR_LONG_INPUT_TIME;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorRageClickCount STRUGGLE_INDICATOR_RAGE_CLICK_COUNT = StruggleIndicatorRageClickCount.STRUGGLE_INDICATOR_RAGE_CLICK_COUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleIndicatorScrollDirectionChangeCount STRUGGLE_INDICATOR_SCROLL_DIRECTION_CHANGE_COUNT = StruggleIndicatorScrollDirectionChangeCount.STRUGGLE_INDICATOR_SCROLL_DIRECTION_CHANGE_COUNT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleScorePage STRUGGLE_SCORE_PAGE = StruggleScorePage.STRUGGLE_SCORE_PAGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final StruggleScoreSession STRUGGLE_SCORE_SESSION = StruggleScoreSession.STRUGGLE_SCORE_SESSION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Task TASK = Task.TASK;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TaskAction TASK_ACTION = TaskAction.TASK_ACTION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TaskHasRatio TASK_HAS_RATIO = TaskHasRatio.TASK_HAS_RATIO;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TaskItem TASK_ITEM = TaskItem.TASK_ITEM;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TaskItemAction TASK_ITEM_ACTION = TaskItemAction.TASK_ITEM_ACTION;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TaskitemHasPage TASKITEM_HAS_PAGE = TaskitemHasPage.TASKITEM_HAS_PAGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TaskitemHasPagename TASKITEM_HAS_PAGENAME = TaskitemHasPagename.TASKITEM_HAS_PAGENAME;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TestDv_2020_07_24 TEST_DV_2020_07_24 = TestDv_2020_07_24.TEST_DV_2020_07_24;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Tmp_0 TMP_0 = Tmp_0.TMP_0;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20010141 TMP_FOR_DEBUG_DELETE_SESSIONS_20010141 = TmpForDebugDeleteSessions_20010141.TMP_FOR_DEBUG_DELETE_SESSIONS_20010141;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20013229 TMP_FOR_DEBUG_DELETE_SESSIONS_20013229 = TmpForDebugDeleteSessions_20013229.TMP_FOR_DEBUG_DELETE_SESSIONS_20013229;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20014116 TMP_FOR_DEBUG_DELETE_SESSIONS_20014116 = TmpForDebugDeleteSessions_20014116.TMP_FOR_DEBUG_DELETE_SESSIONS_20014116;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20014677 TMP_FOR_DEBUG_DELETE_SESSIONS_20014677 = TmpForDebugDeleteSessions_20014677.TMP_FOR_DEBUG_DELETE_SESSIONS_20014677;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2001621 TMP_FOR_DEBUG_DELETE_SESSIONS_2001621 = TmpForDebugDeleteSessions_2001621.TMP_FOR_DEBUG_DELETE_SESSIONS_2001621;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2001646 TMP_FOR_DEBUG_DELETE_SESSIONS_2001646 = TmpForDebugDeleteSessions_2001646.TMP_FOR_DEBUG_DELETE_SESSIONS_2001646;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20017851 TMP_FOR_DEBUG_DELETE_SESSIONS_20017851 = TmpForDebugDeleteSessions_20017851.TMP_FOR_DEBUG_DELETE_SESSIONS_20017851;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20018558 TMP_FOR_DEBUG_DELETE_SESSIONS_20018558 = TmpForDebugDeleteSessions_20018558.TMP_FOR_DEBUG_DELETE_SESSIONS_20018558;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20018769 TMP_FOR_DEBUG_DELETE_SESSIONS_20018769 = TmpForDebugDeleteSessions_20018769.TMP_FOR_DEBUG_DELETE_SESSIONS_20018769;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_20019106 TMP_FOR_DEBUG_DELETE_SESSIONS_20019106 = TmpForDebugDeleteSessions_20019106.TMP_FOR_DEBUG_DELETE_SESSIONS_20019106;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_200343 TMP_FOR_DEBUG_DELETE_SESSIONS_200343 = TmpForDebugDeleteSessions_200343.TMP_FOR_DEBUG_DELETE_SESSIONS_200343;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2005866 TMP_FOR_DEBUG_DELETE_SESSIONS_2005866 = TmpForDebugDeleteSessions_2005866.TMP_FOR_DEBUG_DELETE_SESSIONS_2005866;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2005981 TMP_FOR_DEBUG_DELETE_SESSIONS_2005981 = TmpForDebugDeleteSessions_2005981.TMP_FOR_DEBUG_DELETE_SESSIONS_2005981;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2006763 TMP_FOR_DEBUG_DELETE_SESSIONS_2006763 = TmpForDebugDeleteSessions_2006763.TMP_FOR_DEBUG_DELETE_SESSIONS_2006763;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2007834 TMP_FOR_DEBUG_DELETE_SESSIONS_2007834 = TmpForDebugDeleteSessions_2007834.TMP_FOR_DEBUG_DELETE_SESSIONS_2007834;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpForDebugDeleteSessions_2009120 TMP_FOR_DEBUG_DELETE_SESSIONS_2009120 = TmpForDebugDeleteSessions_2009120.TMP_FOR_DEBUG_DELETE_SESSIONS_2009120;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpSelection_266184216 TMP_SELECTION_266184216 = TmpSelection_266184216.TMP_SELECTION_266184216;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TmpSelection_63943770 TMP_SELECTION_63943770 = TmpSelection_63943770.TMP_SELECTION_63943770;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TrackingConfig TRACKING_CONFIG = TrackingConfig.TRACKING_CONFIG;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final TrackingSetup TRACKING_SETUP = TrackingSetup.TRACKING_SETUP;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Trafficstats TRAFFICSTATS = Trafficstats.TRAFFICSTATS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Trafficstats31d TRAFFICSTATS31D = Trafficstats31d.TRAFFICSTATS31D;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final UnmappedPage UNMAPPED_PAGE = UnmappedPage.UNMAPPED_PAGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Url URL = Url.URL;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final User USER = User.USER;

    /**
     * The table <code>live_core.user_fingerprint</code>.
     */
    public final UserFingerprint USER_FINGERPRINT = UserFingerprint.USER_FINGERPRINT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final UserHasPrivilege USER_HAS_PRIVILEGE = UserHasPrivilege.USER_HAS_PRIVILEGE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final UserHasSaf USER_HAS_SAF = UserHasSaf.USER_HAS_SAF;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final UserHasSite USER_HAS_SITE = UserHasSite.USER_HAS_SITE;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final UserViewedDashboard USER_VIEWED_DASHBOARD = UserViewedDashboard.USER_VIEWED_DASHBOARD;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Useragent USERAGENT = Useragent.USERAGENT;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Useragents2 USERAGENTS2 = Useragents2.USERAGENTS2;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Useragents3 USERAGENTS3 = Useragents3.USERAGENTS3;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Vendor VENDOR = Vendor.VENDOR;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Video VIDEO = Video.VIDEO;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final VideoPageStats VIDEO_PAGE_STATS = VideoPageStats.VIDEO_PAGE_STATS;

    /**
     * Easy access to underlying table in other schemas.
     */
    public final Visitor VISITOR = Visitor.VISITOR;

    /**
     * No further instances allowed
     */
    private LiveCore() {
        super("live_core", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            _SessionSelection._SESSION_SELECTION,
            _TmpUseragentsDv2020_08_06._TMP_USERAGENTS_DV2020_08_06,
            Account.ACCOUNT,
            AdobeAnalyticsFilter.ADOBE_ANALYTICS_FILTER,
            AdobeAnalyticsFilterSession.ADOBE_ANALYTICS_FILTER_SESSION,
            AdobeAnalyticsFilterVisitor.ADOBE_ANALYTICS_FILTER_VISITOR,
            AdobeAnalyticsSuite.ADOBE_ANALYTICS_SUITE,
            AdobeAnalyticsSuiteImportsettings.ADOBE_ANALYTICS_SUITE_IMPORTSETTINGS,
            AggregationPlan.AGGREGATION_PLAN,
            Bucket.BUCKET,
            BucketAlertEmailSetting.BUCKET_ALERT_EMAIL_SETTING,
            BucketCount.BUCKET_COUNT,
            BucketCountBase.BUCKET_COUNT_BASE,
            BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF,
            BucketCountCwav87wdqu.BUCKET_COUNT_CWAV87WDQU,
            BucketCountMdxdlwkdtm.BUCKET_COUNT_MDXDLWKDTM,
            BucketCountVuxuvm8wek.BUCKET_COUNT_VUXUVM8WEK,
            BucketCountXwwlf8vbaw.BUCKET_COUNT_XWWLF8VBAW,
            BucketCountZdth64uzum.BUCKET_COUNT_ZDTH64UZUM,
            BucketTemplate.BUCKET_TEMPLATE,
            CassandraCleanlist.CASSANDRA_CLEANLIST,
            ComscoreFilter.COMSCORE_FILTER,
            ComscoreFilterPids.COMSCORE_FILTER_PIDS,
            Cp_10001Pageimpression.CP_10001_PAGEIMPRESSION,
            Cp_10010Pageimpression.CP_10010_PAGEIMPRESSION,
            Cp_1Pageimpression.CP_1_PAGEIMPRESSION,
            Cp_1Session.CP_1_SESSION,
            Cp_2Pageimpression.CP_2_PAGEIMPRESSION,
            Cp_3338Pageimpression.CP_3338_PAGEIMPRESSION,
            Cp_3338Session.CP_3338_SESSION,
            Cp_3Pageimpression.CP_3_PAGEIMPRESSION,
            Cp_3Session.CP_3_SESSION,
            Cp_4Pageimpression.CP_4_PAGEIMPRESSION,
            Cp_5Pageimpression.CP_5_PAGEIMPRESSION,
            Cp_5Session.CP_5_SESSION,
            CpCount_10001Pageimpression.CP_COUNT_10001_PAGEIMPRESSION,
            CpCount_1Pageimpression.CP_COUNT_1_PAGEIMPRESSION,
            CpCount_1Session.CP_COUNT_1_SESSION,
            CpCount_2Pageimpression.CP_COUNT_2_PAGEIMPRESSION,
            CpCount_3Pageimpression.CP_COUNT_3_PAGEIMPRESSION,
            CpCount_3Session.CP_COUNT_3_SESSION,
            CpCount_4Pageimpression.CP_COUNT_4_PAGEIMPRESSION,
            CpCount_5Pageimpression.CP_COUNT_5_PAGEIMPRESSION,
            CpCount_5Session.CP_COUNT_5_SESSION,
            Customparameter.CUSTOMPARAMETER,
            CustomparameterDomtree.CUSTOMPARAMETER_DOMTREE,
            CustomparameterLucene.CUSTOMPARAMETER_LUCENE,
            CustomparameterPatterndetector.CUSTOMPARAMETER_PATTERNDETECTOR,
            CustomparameterSqlquery.CUSTOMPARAMETER_SQLQUERY,
            DataBaseTest.DATA_BASE_TEST,
            DebugClient.DEBUG_CLIENT,
            DeviceInfoJsonPair.DEVICE_INFO_JSON_PAIR,
            Document.DOCUMENT,
            Element.ELEMENT,
            ElementVisible.ELEMENT_VISIBLE,
            Event.EVENT,
            EventClick.EVENT_CLICK,
            EventFocus.EVENT_FOCUS,
            EventHover.EVENT_HOVER,
            EventTable.EVENT_TABLE,
            ExceptionFilter.EXCEPTION_FILTER,
            Exportqueue.EXPORTQUEUE,
            FormelementAction.FORMELEMENT_ACTION,
            FormelementactionHasTaskitem.FORMELEMENTACTION_HAS_TASKITEM,
            Gesture.GESTURE,
            HeadlessAnswer.HEADLESS_ANSWER,
            HeadlessPollsShowed.HEADLESS_POLLS_SHOWED,
            HeadlessResponseRate.HEADLESS_RESPONSE_RATE,
            HeadlessanswerHasProperty.HEADLESSANSWER_HAS_PROPERTY,
            HistoryTrackingAmount.HISTORY_TRACKING_AMOUNT,
            HistoryTrackingRate.HISTORY_TRACKING_RATE,
            Is24Filter.IS24_FILTER,
            Is24FilterPids.IS24_FILTER_PIDS,
            JsonDatatype.JSON_DATATYPE,
            JsonKey.JSON_KEY,
            JsonValue.JSON_VALUE,
            LogPageHasAnswer.LOG_PAGE_HAS_ANSWER,
            LogSession.LOG_SESSION,
            LogSessionState.LOG_SESSION_STATE,
            MagicCode.MAGIC_CODE,
            MapClick.MAP_CLICK,
            MapClick_3135.MAP_CLICK_3135,
            MapClickBotched.MAP_CLICK_BOTCHED,
            MapClickCleanup.MAP_CLICK_CLEANUP,
            MapClickKp.MAP_CLICK_KP,
            MapClickPathinfo.MAP_CLICK_PATHINFO,
            MapClickPathinfo_11024.MAP_CLICK_PATHINFO_11024,
            MapClickPathinfo_11198.MAP_CLICK_PATHINFO_11198,
            MapClickPathinfo_11689.MAP_CLICK_PATHINFO_11689,
            MapClickPathnode.MAP_CLICK_PATHNODE,
            MapClickSettings.MAP_CLICK_SETTINGS,
            MapFocus.MAP_FOCUS,
            MapMove.MAP_MOVE,
            MapMove_3.MAP_MOVE_3,
            MapScroll.MAP_SCROLL,
            MapVisible.MAP_VISIBLE,
            Mdata.MDATA,
            Metadata.METADATA,
            MobileDevice.MOBILE_DEVICE,
            MobileMetric.MOBILE_METRIC,
            Movement_0t1.MOVEMENT_0T1,
            Movement_10t60.MOVEMENT_10T60,
            Movement_120.MOVEMENT_120,
            Movement_1t2.MOVEMENT_1T2,
            Movement_2t3.MOVEMENT_2T3,
            Movement_3t4.MOVEMENT_3T4,
            Movement_4t5.MOVEMENT_4T5,
            Movement_5t10.MOVEMENT_5T10,
            Movement_60t120.MOVEMENT_60T120,
            Movementmap.MOVEMENTMAP,
            Page.PAGE,
            PageFilter.PAGE_FILTER,
            PageHasAnswer.PAGE_HAS_ANSWER,
            PageHasEtlvisitorreplayreadyevent.PAGE_HAS_ETLVISITORREPLAYREADYEVENT,
            PageHasGesture.PAGE_HAS_GESTURE,
            PageHasResource.PAGE_HAS_RESOURCE,
            PageHasRespondent.PAGE_HAS_RESPONDENT,
            PageHasRespondentProd.PAGE_HAS_RESPONDENT_PROD,
            PageHasRespondentoldVoc_13071.PAGE_HAS_RESPONDENTOLD_VOC_13071,
            PageHasTag.PAGE_HAS_TAG,
            PageHasVideo.PAGE_HAS_VIDEO,
            PageName.PAGE_NAME,
            PageNameBlocklist.PAGE_NAME_BLOCKLIST,
            PageNameImport.PAGE_NAME_IMPORT,
            PageStats.PAGE_STATS,
            PagenamesToDelete.PAGENAMES_TO_DELETE,
            Privilege.PRIVILEGE,
            PropertyValues.PROPERTY_VALUES,
            Questionnaire.QUESTIONNAIRE,
            QuestionnaireAlert.QUESTIONNAIRE_ALERT,
            QuestionnaireCrypt.QUESTIONNAIRE_CRYPT,
            QuestionnaireElement.QUESTIONNAIRE_ELEMENT,
            QuestionnaireHasExport.QUESTIONNAIRE_HAS_EXPORT,
            QuestionnaireHasFile.QUESTIONNAIRE_HAS_FILE,
            QuestionnaireLayout.QUESTIONNAIRE_LAYOUT,
            QuestionnaireType.QUESTIONNAIRE_TYPE,
            Raster.RASTER,
            Ratio.RATIO,
            RatioType.RATIO_TYPE,
            ResourceExcludeBot.RESOURCE_EXCLUDE_BOT,
            ResourceExcludeHost.RESOURCE_EXCLUDE_HOST,
            ResourceExcludeKeyword.RESOURCE_EXCLUDE_KEYWORD,
            ResourceHasParent.RESOURCE_HAS_PARENT,
            ResourceIncludeProtocol.RESOURCE_INCLUDE_PROTOCOL,
            ResourceOld.RESOURCE_OLD,
            ResourceReimport.RESOURCE_REIMPORT,
            ResourceRule.RESOURCE_RULE,
            SafHasSegments.SAF_HAS_SEGMENTS,
            SafSegmentHasPage.SAF_SEGMENT_HAS_PAGE,
            SchemaInfo.SCHEMA_INFO,
            Scrollingmap.SCROLLINGMAP,
            Server.SERVER,
            Session.SESSION,
            SessionHasMetadata.SESSION_HAS_METADATA,
            SessionHasMobileDevice.SESSION_HAS_MOBILE_DEVICE,
            SessionHasPagename.SESSION_HAS_PAGENAME,
            SessionHasResource.SESSION_HAS_RESOURCE,
            SessionReimport.SESSION_REIMPORT,
            SessionSelection.SESSION_SELECTION,
            Sessionstats24h.SESSIONSTATS24H,
            Settings.SETTINGS,
            Site.SITE,
            SiteApiFiles.SITE_API_FILES,
            SiteHasVendor.SITE_HAS_VENDOR,
            Sitestats.SITESTATS,
            StageJsonPair.STAGE_JSON_PAIR,
            StoredFilter.STORED_FILTER,
            StruggleIndicatorDeadClickCount.STRUGGLE_INDICATOR_DEAD_CLICK_COUNT,
            StruggleIndicatorDomloadTime.STRUGGLE_INDICATOR_DOMLOAD_TIME,
            StruggleIndicatorErrorMessageCount.STRUGGLE_INDICATOR_ERROR_MESSAGE_COUNT,
            StruggleIndicatorErrorPage.STRUGGLE_INDICATOR_ERROR_PAGE,
            StruggleIndicatorFormFieldAbandonment.STRUGGLE_INDICATOR_FORM_FIELD_ABANDONMENT,
            StruggleIndicatorFormFieldModificationCount.STRUGGLE_INDICATOR_FORM_FIELD_MODIFICATION_COUNT,
            StruggleIndicatorFunnelStepRepetition.STRUGGLE_INDICATOR_FUNNEL_STEP_REPETITION,
            StruggleIndicatorJsErrorCount.STRUGGLE_INDICATOR_JS_ERROR_COUNT,
            StruggleIndicatorLongInputTime.STRUGGLE_INDICATOR_LONG_INPUT_TIME,
            StruggleIndicatorRageClickCount.STRUGGLE_INDICATOR_RAGE_CLICK_COUNT,
            StruggleIndicatorScrollDirectionChangeCount.STRUGGLE_INDICATOR_SCROLL_DIRECTION_CHANGE_COUNT,
            StruggleScorePage.STRUGGLE_SCORE_PAGE,
            StruggleScoreSession.STRUGGLE_SCORE_SESSION,
            Tag.TAG,
            Task.TASK,
            TaskAction.TASK_ACTION,
            TaskHasRatio.TASK_HAS_RATIO,
            TaskItem.TASK_ITEM,
            TaskItemAction.TASK_ITEM_ACTION,
            TaskitemHasPage.TASKITEM_HAS_PAGE,
            TaskitemHasPagename.TASKITEM_HAS_PAGENAME,
            TestDv_2020_07_24.TEST_DV_2020_07_24,
            Tmp_0.TMP_0,
            TmpForDebugDeleteSessions_20010141.TMP_FOR_DEBUG_DELETE_SESSIONS_20010141,
            TmpForDebugDeleteSessions_20013229.TMP_FOR_DEBUG_DELETE_SESSIONS_20013229,
            TmpForDebugDeleteSessions_20014116.TMP_FOR_DEBUG_DELETE_SESSIONS_20014116,
            TmpForDebugDeleteSessions_20014677.TMP_FOR_DEBUG_DELETE_SESSIONS_20014677,
            TmpForDebugDeleteSessions_2001621.TMP_FOR_DEBUG_DELETE_SESSIONS_2001621,
            TmpForDebugDeleteSessions_2001646.TMP_FOR_DEBUG_DELETE_SESSIONS_2001646,
            TmpForDebugDeleteSessions_20017851.TMP_FOR_DEBUG_DELETE_SESSIONS_20017851,
            TmpForDebugDeleteSessions_20018558.TMP_FOR_DEBUG_DELETE_SESSIONS_20018558,
            TmpForDebugDeleteSessions_20018769.TMP_FOR_DEBUG_DELETE_SESSIONS_20018769,
            TmpForDebugDeleteSessions_20019106.TMP_FOR_DEBUG_DELETE_SESSIONS_20019106,
            TmpForDebugDeleteSessions_200343.TMP_FOR_DEBUG_DELETE_SESSIONS_200343,
            TmpForDebugDeleteSessions_2005866.TMP_FOR_DEBUG_DELETE_SESSIONS_2005866,
            TmpForDebugDeleteSessions_2005981.TMP_FOR_DEBUG_DELETE_SESSIONS_2005981,
            TmpForDebugDeleteSessions_2006763.TMP_FOR_DEBUG_DELETE_SESSIONS_2006763,
            TmpForDebugDeleteSessions_2007834.TMP_FOR_DEBUG_DELETE_SESSIONS_2007834,
            TmpForDebugDeleteSessions_2009120.TMP_FOR_DEBUG_DELETE_SESSIONS_2009120,
            TmpSelection_266184216.TMP_SELECTION_266184216,
            TmpSelection_63943770.TMP_SELECTION_63943770,
            TrackingConfig.TRACKING_CONFIG,
            TrackingSetup.TRACKING_SETUP,
            Trafficstats.TRAFFICSTATS,
            Trafficstats31d.TRAFFICSTATS31D,
            UnmappedPage.UNMAPPED_PAGE,
            Url.URL,
            User.USER,
            UserFingerprint.USER_FINGERPRINT,
            UserHasPrivilege.USER_HAS_PRIVILEGE,
            UserHasSaf.USER_HAS_SAF,
            UserHasSite.USER_HAS_SITE,
            UserViewedDashboard.USER_VIEWED_DASHBOARD,
            Useragent.USERAGENT,
            Useragents2.USERAGENTS2,
            Useragents3.USERAGENTS3,
            Vendor.VENDOR,
            Video.VIDEO,
            VideoPageStats.VIDEO_PAGE_STATS,
            Visitor.VISITOR
        );
    }
}
