/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables;


import com.verint.mpathy.db.live.Live;
import com.verint.mpathy.db.live.tables.records.Cp_10001PageimpressionRecord;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cp_10001Pageimpression extends TableImpl<Cp_10001PageimpressionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live.cp_10001_pageimpression</code>
     */
    public static final Cp_10001Pageimpression CP_10001_PAGEIMPRESSION = new Cp_10001Pageimpression();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Cp_10001PageimpressionRecord> getRecordType() {
        return Cp_10001PageimpressionRecord.class;
    }

    /**
     * The column <code>live.cp_10001_pageimpression.idpage</code>.
     */
    public final TableField<Cp_10001PageimpressionRecord, BigDecimal> IDPAGE = createField(DSL.name("idpage"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>live.cp_10001_pageimpression.idcp</code>.
     */
    public final TableField<Cp_10001PageimpressionRecord, Long> IDCP = createField(DSL.name("idcp"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>live.cp_10001_pageimpression.idvalue</code>.
     */
    public final TableField<Cp_10001PageimpressionRecord, BigDecimal> IDVALUE = createField(DSL.name("idvalue"), SQLDataType.NUMERIC, this, "");

    private Cp_10001Pageimpression(Name alias, Table<Cp_10001PageimpressionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cp_10001Pageimpression(Name alias, Table<Cp_10001PageimpressionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>live.cp_10001_pageimpression</code> table
     * reference
     */
    public Cp_10001Pageimpression(String alias) {
        this(DSL.name(alias), CP_10001_PAGEIMPRESSION);
    }

    /**
     * Create an aliased <code>live.cp_10001_pageimpression</code> table
     * reference
     */
    public Cp_10001Pageimpression(Name alias) {
        this(alias, CP_10001_PAGEIMPRESSION);
    }

    /**
     * Create a <code>live.cp_10001_pageimpression</code> table reference
     */
    public Cp_10001Pageimpression() {
        this(DSL.name("cp_10001_pageimpression"), null);
    }

    public <O extends Record> Cp_10001Pageimpression(Table<O> child, ForeignKey<O, Cp_10001PageimpressionRecord> key) {
        super(child, key, CP_10001_PAGEIMPRESSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Live.LIVE;
    }

    @Override
    public Cp_10001Pageimpression as(String alias) {
        return new Cp_10001Pageimpression(DSL.name(alias), this);
    }

    @Override
    public Cp_10001Pageimpression as(Name alias) {
        return new Cp_10001Pageimpression(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cp_10001Pageimpression rename(String name) {
        return new Cp_10001Pageimpression(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cp_10001Pageimpression rename(Name name) {
        return new Cp_10001Pageimpression(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<BigDecimal, Long, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
