/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables;


import com.verint.mpathy.db.live.Live;
import com.verint.mpathy.db.live.tables.records.Movement_2t3Record;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Movement_2t3 extends TableImpl<Movement_2t3Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>live.movement_2t3</code>
     */
    public static final Movement_2t3 MOVEMENT_2T3 = new Movement_2t3();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Movement_2t3Record> getRecordType() {
        return Movement_2t3Record.class;
    }

    /**
     * The column <code>live.movement_2t3.idsite</code>. Technical foreign key
     * to the "site" table and a foreign key to "site".
     */
    public final TableField<Movement_2t3Record, Integer> IDSITE = createField(DSL.name("idsite"), SQLDataType.INTEGER.nullable(false), this, "Technical foreign key to the \"site\" table and a foreign key to \"site\".");

    /**
     * The column <code>live.movement_2t3.idpage</code>. Technical foreign key
     * to the "page" table and a foreign key to "page".
     */
    public final TableField<Movement_2t3Record, BigDecimal> IDPAGE = createField(DSL.name("idpage"), SQLDataType.NUMERIC.nullable(false), this, "Technical foreign key to the \"page\" table and a foreign key to \"page\".");

    /**
     * The column <code>live.movement_2t3.move</code>. Accumulated moves from
     * "map_move between 2 and 3 seconds.
     */
    public final TableField<Movement_2t3Record, String> MOVE = createField(DSL.name("move"), SQLDataType.CLOB, this, "Accumulated moves from \"map_move between 2 and 3 seconds.");

    private Movement_2t3(Name alias, Table<Movement_2t3Record> aliased) {
        this(alias, aliased, null);
    }

    private Movement_2t3(Name alias, Table<Movement_2t3Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>live.movement_2t3</code> table reference
     */
    public Movement_2t3(String alias) {
        this(DSL.name(alias), MOVEMENT_2T3);
    }

    /**
     * Create an aliased <code>live.movement_2t3</code> table reference
     */
    public Movement_2t3(Name alias) {
        this(alias, MOVEMENT_2T3);
    }

    /**
     * Create a <code>live.movement_2t3</code> table reference
     */
    public Movement_2t3() {
        this(DSL.name("movement_2t3"), null);
    }

    public <O extends Record> Movement_2t3(Table<O> child, ForeignKey<O, Movement_2t3Record> key) {
        super(child, key, MOVEMENT_2T3);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Live.LIVE;
    }

    @Override
    public Movement_2t3 as(String alias) {
        return new Movement_2t3(DSL.name(alias), this);
    }

    @Override
    public Movement_2t3 as(Name alias) {
        return new Movement_2t3(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Movement_2t3 rename(String name) {
        return new Movement_2t3(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Movement_2t3 rename(Name name) {
        return new Movement_2t3(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, BigDecimal, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
