/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.BucketCountBdtcjn6dtf;

import java.math.BigDecimal;
import java.time.LocalTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BucketCountBdtcjn6dtfRecord extends TableRecordImpl<BucketCountBdtcjn6dtfRecord> implements Record4<Integer, BigDecimal, LocalTime, LocalTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.bucket_count_bDTcJn6dTf.idsite</code>.
     */
    public void setIdsite(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.bucket_count_bDTcJn6dTf.idsite</code>.
     */
    public Integer getIdsite() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>live.bucket_count_bDTcJn6dTf.idbucket</code>.
     */
    public void setIdbucket(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.bucket_count_bDTcJn6dTf.idbucket</code>.
     */
    public BigDecimal getIdbucket() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>live.bucket_count_bDTcJn6dTf.start_date</code>.
     */
    public void setStartDate(LocalTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.bucket_count_bDTcJn6dTf.start_date</code>.
     */
    public LocalTime getStartDate() {
        return (LocalTime) get(2);
    }

    /**
     * Setter for <code>live.bucket_count_bDTcJn6dTf.stop_date</code>.
     */
    public void setStopDate(LocalTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>live.bucket_count_bDTcJn6dTf.stop_date</code>.
     */
    public LocalTime getStopDate() {
        return (LocalTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, BigDecimal, LocalTime, LocalTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, BigDecimal, LocalTime, LocalTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF.IDSITE;
    }

    @Override
    public Field<BigDecimal> field2() {
        return BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF.IDBUCKET;
    }

    @Override
    public Field<LocalTime> field3() {
        return BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF.START_DATE;
    }

    @Override
    public Field<LocalTime> field4() {
        return BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF.STOP_DATE;
    }

    @Override
    public Integer component1() {
        return getIdsite();
    }

    @Override
    public BigDecimal component2() {
        return getIdbucket();
    }

    @Override
    public LocalTime component3() {
        return getStartDate();
    }

    @Override
    public LocalTime component4() {
        return getStopDate();
    }

    @Override
    public Integer value1() {
        return getIdsite();
    }

    @Override
    public BigDecimal value2() {
        return getIdbucket();
    }

    @Override
    public LocalTime value3() {
        return getStartDate();
    }

    @Override
    public LocalTime value4() {
        return getStopDate();
    }

    @Override
    public BucketCountBdtcjn6dtfRecord value1(Integer value) {
        setIdsite(value);
        return this;
    }

    @Override
    public BucketCountBdtcjn6dtfRecord value2(BigDecimal value) {
        setIdbucket(value);
        return this;
    }

    @Override
    public BucketCountBdtcjn6dtfRecord value3(LocalTime value) {
        setStartDate(value);
        return this;
    }

    @Override
    public BucketCountBdtcjn6dtfRecord value4(LocalTime value) {
        setStopDate(value);
        return this;
    }

    @Override
    public BucketCountBdtcjn6dtfRecord values(Integer value1, BigDecimal value2, LocalTime value3, LocalTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BucketCountBdtcjn6dtfRecord
     */
    public BucketCountBdtcjn6dtfRecord() {
        super(BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF);
    }

    /**
     * Create a detached, initialised BucketCountBdtcjn6dtfRecord
     */
    public BucketCountBdtcjn6dtfRecord(Integer idsite, BigDecimal idbucket, LocalTime startDate, LocalTime stopDate) {
        super(BucketCountBdtcjn6dtf.BUCKET_COUNT_BDTCJN6DTF);

        setIdsite(idsite);
        setIdbucket(idbucket);
        setStartDate(startDate);
        setStopDate(stopDate);
    }
}
