/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.MapClickCleanup;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapClickCleanupRecord extends TableRecordImpl<MapClickCleanupRecord> implements Record11<BigDecimal, BigDecimal, Integer, Object, Long, String, Long, String, Object, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.map_click_cleanup.idpage</code>.
     */
    public void setIdpage(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.idpage</code>.
     */
    public BigDecimal getIdpage() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>live.map_click_cleanup.idsession</code>.
     */
    public void setIdsession(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.idsession</code>.
     */
    public BigDecimal getIdsession() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>live.map_click_cleanup.idsite</code>.
     */
    public void setIdsite(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.idsite</code>.
     */
    public Integer getIdsite() {
        return (Integer) get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setPoint(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getPoint() {
        return get(3);
    }

    /**
     * Setter for <code>live.map_click_cleanup.time</code>.
     */
    public void setTime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.time</code>.
     */
    public Long getTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>live.map_click_cleanup.tagname</code>.
     */
    public void setTagname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.tagname</code>.
     */
    public String getTagname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>live.map_click_cleanup.viewport_width</code>.
     */
    public void setViewportWidth(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.viewport_width</code>.
     */
    public Long getViewportWidth() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>live.map_click_cleanup.xpath</code>.
     */
    public void setXpath(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.xpath</code>.
     */
    public String getXpath() {
        return (String) get(7);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setRelativePoint(Object value) {
        set(8, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getRelativePoint() {
        return get(8);
    }

    /**
     * Setter for <code>live.map_click_cleanup.width</code>.
     */
    public void setWidth(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.width</code>.
     */
    public Integer getWidth() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>live.map_click_cleanup.height</code>.
     */
    public void setHeight(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>live.map_click_cleanup.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<BigDecimal, BigDecimal, Integer, Object, Long, String, Long, String, Object, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<BigDecimal, BigDecimal, Integer, Object, Long, String, Long, String, Object, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.IDPAGE;
    }

    @Override
    public Field<BigDecimal> field2() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.IDSESSION;
    }

    @Override
    public Field<Integer> field3() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.IDSITE;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.POINT;
    }

    @Override
    public Field<Long> field5() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.TIME;
    }

    @Override
    public Field<String> field6() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.TAGNAME;
    }

    @Override
    public Field<Long> field7() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.VIEWPORT_WIDTH;
    }

    @Override
    public Field<String> field8() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.XPATH;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field9() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.RELATIVE_POINT;
    }

    @Override
    public Field<Integer> field10() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.WIDTH;
    }

    @Override
    public Field<Integer> field11() {
        return MapClickCleanup.MAP_CLICK_CLEANUP.HEIGHT;
    }

    @Override
    public BigDecimal component1() {
        return getIdpage();
    }

    @Override
    public BigDecimal component2() {
        return getIdsession();
    }

    @Override
    public Integer component3() {
        return getIdsite();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getPoint();
    }

    @Override
    public Long component5() {
        return getTime();
    }

    @Override
    public String component6() {
        return getTagname();
    }

    @Override
    public Long component7() {
        return getViewportWidth();
    }

    @Override
    public String component8() {
        return getXpath();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object component9() {
        return getRelativePoint();
    }

    @Override
    public Integer component10() {
        return getWidth();
    }

    @Override
    public Integer component11() {
        return getHeight();
    }

    @Override
    public BigDecimal value1() {
        return getIdpage();
    }

    @Override
    public BigDecimal value2() {
        return getIdsession();
    }

    @Override
    public Integer value3() {
        return getIdsite();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getPoint();
    }

    @Override
    public Long value5() {
        return getTime();
    }

    @Override
    public String value6() {
        return getTagname();
    }

    @Override
    public Long value7() {
        return getViewportWidth();
    }

    @Override
    public String value8() {
        return getXpath();
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public Object value9() {
        return getRelativePoint();
    }

    @Override
    public Integer value10() {
        return getWidth();
    }

    @Override
    public Integer value11() {
        return getHeight();
    }

    @Override
    public MapClickCleanupRecord value1(BigDecimal value) {
        setIdpage(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value2(BigDecimal value) {
        setIdsession(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value3(Integer value) {
        setIdsite(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public MapClickCleanupRecord value4(Object value) {
        setPoint(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value5(Long value) {
        setTime(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value6(String value) {
        setTagname(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value7(Long value) {
        setViewportWidth(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value8(String value) {
        setXpath(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    @Override
    public MapClickCleanupRecord value9(Object value) {
        setRelativePoint(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value10(Integer value) {
        setWidth(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord value11(Integer value) {
        setHeight(value);
        return this;
    }

    @Override
    public MapClickCleanupRecord values(BigDecimal value1, BigDecimal value2, Integer value3, Object value4, Long value5, String value6, Long value7, String value8, Object value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapClickCleanupRecord
     */
    public MapClickCleanupRecord() {
        super(MapClickCleanup.MAP_CLICK_CLEANUP);
    }

    /**
     * Create a detached, initialised MapClickCleanupRecord
     */
    public MapClickCleanupRecord(BigDecimal idpage, BigDecimal idsession, Integer idsite, Object point, Long time, String tagname, Long viewportWidth, String xpath, Object relativePoint, Integer width, Integer height) {
        super(MapClickCleanup.MAP_CLICK_CLEANUP);

        setIdpage(idpage);
        setIdsession(idsession);
        setIdsite(idsite);
        setPoint(point);
        setTime(time);
        setTagname(tagname);
        setViewportWidth(viewportWidth);
        setXpath(xpath);
        setRelativePoint(relativePoint);
        setWidth(width);
        setHeight(height);
    }
}
