/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.MapFocus;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapFocusRecord extends TableRecordImpl<MapFocusRecord> implements Record5<Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.map_focus.idsite</code>.
     */
    public void setIdsite(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.map_focus.idsite</code>.
     */
    public Integer getIdsite() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>live.map_focus.x</code>.
     */
    public void setX(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.map_focus.x</code>.
     */
    public Integer getX() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>live.map_focus.y</code>.
     */
    public void setY(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.map_focus.y</code>.
     */
    public Integer getY() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>live.map_focus.sum</code>.
     */
    public void setSum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>live.map_focus.sum</code>.
     */
    public Integer getSum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>live.map_focus.sessions</code>.
     */
    public void setSessions(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>live.map_focus.sessions</code>.
     */
    public String getSessions() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MapFocus.MAP_FOCUS.IDSITE;
    }

    @Override
    public Field<Integer> field2() {
        return MapFocus.MAP_FOCUS.X;
    }

    @Override
    public Field<Integer> field3() {
        return MapFocus.MAP_FOCUS.Y;
    }

    @Override
    public Field<Integer> field4() {
        return MapFocus.MAP_FOCUS.SUM;
    }

    @Override
    public Field<String> field5() {
        return MapFocus.MAP_FOCUS.SESSIONS;
    }

    @Override
    public Integer component1() {
        return getIdsite();
    }

    @Override
    public Integer component2() {
        return getX();
    }

    @Override
    public Integer component3() {
        return getY();
    }

    @Override
    public Integer component4() {
        return getSum();
    }

    @Override
    public String component5() {
        return getSessions();
    }

    @Override
    public Integer value1() {
        return getIdsite();
    }

    @Override
    public Integer value2() {
        return getX();
    }

    @Override
    public Integer value3() {
        return getY();
    }

    @Override
    public Integer value4() {
        return getSum();
    }

    @Override
    public String value5() {
        return getSessions();
    }

    @Override
    public MapFocusRecord value1(Integer value) {
        setIdsite(value);
        return this;
    }

    @Override
    public MapFocusRecord value2(Integer value) {
        setX(value);
        return this;
    }

    @Override
    public MapFocusRecord value3(Integer value) {
        setY(value);
        return this;
    }

    @Override
    public MapFocusRecord value4(Integer value) {
        setSum(value);
        return this;
    }

    @Override
    public MapFocusRecord value5(String value) {
        setSessions(value);
        return this;
    }

    @Override
    public MapFocusRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapFocusRecord
     */
    public MapFocusRecord() {
        super(MapFocus.MAP_FOCUS);
    }

    /**
     * Create a detached, initialised MapFocusRecord
     */
    public MapFocusRecord(Integer idsite, Integer x, Integer y, Integer sum, String sessions) {
        super(MapFocus.MAP_FOCUS);

        setIdsite(idsite);
        setX(x);
        setY(y);
        setSum(sum);
        setSessions(sessions);
    }
}
