/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.MobileDevice;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * The table contains all information about static information of a mobile
 * device.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MobileDeviceRecord extends TableRecordImpl<MobileDeviceRecord> implements Record6<Long, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.mobile_device.idmobile_device</code>. Primary key.
     */
    public void setIdmobileDevice(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.mobile_device.idmobile_device</code>. Primary key.
     */
    public Long getIdmobileDevice() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>live.mobile_device.device_model</code>. Model name of
     * mobile device group.
     */
    public void setDeviceModel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.mobile_device.device_model</code>. Model name of
     * mobile device group.
     */
    public String getDeviceModel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>live.mobile_device.device_family</code>. Family name of
     * mobile device group.
     */
    public void setDeviceFamily(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.mobile_device.device_family</code>. Family name of
     * mobile device group.
     */
    public String getDeviceFamily() {
        return (String) get(2);
    }

    /**
     * Setter for <code>live.mobile_device.os_name</code>. Name of the mobile
     * operation system.
     */
    public void setOsName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>live.mobile_device.os_name</code>. Name of the mobile
     * operation system.
     */
    public String getOsName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>live.mobile_device.os_version</code>. Version of the
     * mobile operation system.
     */
    public void setOsVersion(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>live.mobile_device.os_version</code>. Version of the
     * mobile operation system.
     */
    public String getOsVersion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>live.mobile_device.device_type</code>. Device type of
     * mobile device group.
     */
    public void setDeviceType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>live.mobile_device.device_type</code>. Device type of
     * mobile device group.
     */
    public String getDeviceType() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MobileDevice.MOBILE_DEVICE.IDMOBILE_DEVICE;
    }

    @Override
    public Field<String> field2() {
        return MobileDevice.MOBILE_DEVICE.DEVICE_MODEL;
    }

    @Override
    public Field<String> field3() {
        return MobileDevice.MOBILE_DEVICE.DEVICE_FAMILY;
    }

    @Override
    public Field<String> field4() {
        return MobileDevice.MOBILE_DEVICE.OS_NAME;
    }

    @Override
    public Field<String> field5() {
        return MobileDevice.MOBILE_DEVICE.OS_VERSION;
    }

    @Override
    public Field<String> field6() {
        return MobileDevice.MOBILE_DEVICE.DEVICE_TYPE;
    }

    @Override
    public Long component1() {
        return getIdmobileDevice();
    }

    @Override
    public String component2() {
        return getDeviceModel();
    }

    @Override
    public String component3() {
        return getDeviceFamily();
    }

    @Override
    public String component4() {
        return getOsName();
    }

    @Override
    public String component5() {
        return getOsVersion();
    }

    @Override
    public String component6() {
        return getDeviceType();
    }

    @Override
    public Long value1() {
        return getIdmobileDevice();
    }

    @Override
    public String value2() {
        return getDeviceModel();
    }

    @Override
    public String value3() {
        return getDeviceFamily();
    }

    @Override
    public String value4() {
        return getOsName();
    }

    @Override
    public String value5() {
        return getOsVersion();
    }

    @Override
    public String value6() {
        return getDeviceType();
    }

    @Override
    public MobileDeviceRecord value1(Long value) {
        setIdmobileDevice(value);
        return this;
    }

    @Override
    public MobileDeviceRecord value2(String value) {
        setDeviceModel(value);
        return this;
    }

    @Override
    public MobileDeviceRecord value3(String value) {
        setDeviceFamily(value);
        return this;
    }

    @Override
    public MobileDeviceRecord value4(String value) {
        setOsName(value);
        return this;
    }

    @Override
    public MobileDeviceRecord value5(String value) {
        setOsVersion(value);
        return this;
    }

    @Override
    public MobileDeviceRecord value6(String value) {
        setDeviceType(value);
        return this;
    }

    @Override
    public MobileDeviceRecord values(Long value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MobileDeviceRecord
     */
    public MobileDeviceRecord() {
        super(MobileDevice.MOBILE_DEVICE);
    }

    /**
     * Create a detached, initialised MobileDeviceRecord
     */
    public MobileDeviceRecord(Long idmobileDevice, String deviceModel, String deviceFamily, String osName, String osVersion, String deviceType) {
        super(MobileDevice.MOBILE_DEVICE);

        setIdmobileDevice(idmobileDevice);
        setDeviceModel(deviceModel);
        setDeviceFamily(deviceFamily);
        setOsName(osName);
        setOsVersion(osVersion);
        setDeviceType(deviceType);
    }
}
