/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.PagenamesToDelete;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagenamesToDeleteRecord extends TableRecordImpl<PagenamesToDeleteRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.pagenames_to_delete.idpage_name</code>.
     */
    public void setIdpageName(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.pagenames_to_delete.idpage_name</code>.
     */
    public Long getIdpageName() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PagenamesToDelete.PAGENAMES_TO_DELETE.IDPAGE_NAME;
    }

    @Override
    public Long component1() {
        return getIdpageName();
    }

    @Override
    public Long value1() {
        return getIdpageName();
    }

    @Override
    public PagenamesToDeleteRecord value1(Long value) {
        setIdpageName(value);
        return this;
    }

    @Override
    public PagenamesToDeleteRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PagenamesToDeleteRecord
     */
    public PagenamesToDeleteRecord() {
        super(PagenamesToDelete.PAGENAMES_TO_DELETE);
    }

    /**
     * Create a detached, initialised PagenamesToDeleteRecord
     */
    public PagenamesToDeleteRecord(Long idpageName) {
        super(PagenamesToDelete.PAGENAMES_TO_DELETE);

        setIdpageName(idpageName);
    }
}
