/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.SessionHasMobileDevice;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * The table contains the reference between a session and his mobile device
 * information.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionHasMobileDeviceRecord extends TableRecordImpl<SessionHasMobileDeviceRecord> implements Record2<Long, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.session_has_mobile_device.idsession</code>. The
     * session reference is part of the primary key.
     */
    public void setIdsession(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.session_has_mobile_device.idsession</code>. The
     * session reference is part of the primary key.
     */
    public Long getIdsession() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>live.session_has_mobile_device.idmobile_device</code>.
     * The foreign key to the "mobile_device" table is part of the primary key.
     */
    public void setIdmobileDevice(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.session_has_mobile_device.idmobile_device</code>.
     * The foreign key to the "mobile_device" table is part of the primary key.
     */
    public BigDecimal getIdmobileDevice() {
        return (BigDecimal) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, BigDecimal> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, BigDecimal> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SessionHasMobileDevice.SESSION_HAS_MOBILE_DEVICE.IDSESSION;
    }

    @Override
    public Field<BigDecimal> field2() {
        return SessionHasMobileDevice.SESSION_HAS_MOBILE_DEVICE.IDMOBILE_DEVICE;
    }

    @Override
    public Long component1() {
        return getIdsession();
    }

    @Override
    public BigDecimal component2() {
        return getIdmobileDevice();
    }

    @Override
    public Long value1() {
        return getIdsession();
    }

    @Override
    public BigDecimal value2() {
        return getIdmobileDevice();
    }

    @Override
    public SessionHasMobileDeviceRecord value1(Long value) {
        setIdsession(value);
        return this;
    }

    @Override
    public SessionHasMobileDeviceRecord value2(BigDecimal value) {
        setIdmobileDevice(value);
        return this;
    }

    @Override
    public SessionHasMobileDeviceRecord values(Long value1, BigDecimal value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionHasMobileDeviceRecord
     */
    public SessionHasMobileDeviceRecord() {
        super(SessionHasMobileDevice.SESSION_HAS_MOBILE_DEVICE);
    }

    /**
     * Create a detached, initialised SessionHasMobileDeviceRecord
     */
    public SessionHasMobileDeviceRecord(Long idsession, BigDecimal idmobileDevice) {
        super(SessionHasMobileDevice.SESSION_HAS_MOBILE_DEVICE);

        setIdsession(idsession);
        setIdmobileDevice(idmobileDevice);
    }
}
