/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.SessionHasMetadata;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionHasMetadataRecord extends TableRecordImpl<SessionHasMetadataRecord> implements Record5<Long, BigDecimal, Long, BigDecimal, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.session_has_metadata.idsession_has_metadata</code>.
     */
    public void setIdsessionHasMetadata(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.session_has_metadata.idsession_has_metadata</code>.
     */
    public Long getIdsessionHasMetadata() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>live.session_has_metadata.idsession</code>.
     */
    public void setIdsession(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.session_has_metadata.idsession</code>.
     */
    public BigDecimal getIdsession() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>live.session_has_metadata.idmetadata</code>.
     */
    public void setIdmetadata(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.session_has_metadata.idmetadata</code>.
     */
    public Long getIdmetadata() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>live.session_has_metadata.iduser</code>.
     */
    public void setIduser(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>live.session_has_metadata.iduser</code>.
     */
    public BigDecimal getIduser() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>live.session_has_metadata.evcounter</code>.
     */
    public void setEvcounter(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>live.session_has_metadata.evcounter</code>.
     */
    public Long getEvcounter() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, BigDecimal, Long, BigDecimal, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, BigDecimal, Long, BigDecimal, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SessionHasMetadata.SESSION_HAS_METADATA.IDSESSION_HAS_METADATA;
    }

    @Override
    public Field<BigDecimal> field2() {
        return SessionHasMetadata.SESSION_HAS_METADATA.IDSESSION;
    }

    @Override
    public Field<Long> field3() {
        return SessionHasMetadata.SESSION_HAS_METADATA.IDMETADATA;
    }

    @Override
    public Field<BigDecimal> field4() {
        return SessionHasMetadata.SESSION_HAS_METADATA.IDUSER;
    }

    @Override
    public Field<Long> field5() {
        return SessionHasMetadata.SESSION_HAS_METADATA.EVCOUNTER;
    }

    @Override
    public Long component1() {
        return getIdsessionHasMetadata();
    }

    @Override
    public BigDecimal component2() {
        return getIdsession();
    }

    @Override
    public Long component3() {
        return getIdmetadata();
    }

    @Override
    public BigDecimal component4() {
        return getIduser();
    }

    @Override
    public Long component5() {
        return getEvcounter();
    }

    @Override
    public Long value1() {
        return getIdsessionHasMetadata();
    }

    @Override
    public BigDecimal value2() {
        return getIdsession();
    }

    @Override
    public Long value3() {
        return getIdmetadata();
    }

    @Override
    public BigDecimal value4() {
        return getIduser();
    }

    @Override
    public Long value5() {
        return getEvcounter();
    }

    @Override
    public SessionHasMetadataRecord value1(Long value) {
        setIdsessionHasMetadata(value);
        return this;
    }

    @Override
    public SessionHasMetadataRecord value2(BigDecimal value) {
        setIdsession(value);
        return this;
    }

    @Override
    public SessionHasMetadataRecord value3(Long value) {
        setIdmetadata(value);
        return this;
    }

    @Override
    public SessionHasMetadataRecord value4(BigDecimal value) {
        setIduser(value);
        return this;
    }

    @Override
    public SessionHasMetadataRecord value5(Long value) {
        setEvcounter(value);
        return this;
    }

    @Override
    public SessionHasMetadataRecord values(Long value1, BigDecimal value2, Long value3, BigDecimal value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionHasMetadataRecord
     */
    public SessionHasMetadataRecord() {
        super(SessionHasMetadata.SESSION_HAS_METADATA);
    }

    /**
     * Create a detached, initialised SessionHasMetadataRecord
     */
    public SessionHasMetadataRecord(Long idsessionHasMetadata, BigDecimal idsession, Long idmetadata, BigDecimal iduser, Long evcounter) {
        super(SessionHasMetadata.SESSION_HAS_METADATA);

        setIdsessionHasMetadata(idsessionHasMetadata);
        setIdsession(idsession);
        setIdmetadata(idmetadata);
        setIduser(iduser);
        setEvcounter(evcounter);
    }
}
