/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.Sessionstats24h;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sessionstats24hRecord extends TableRecordImpl<Sessionstats24hRecord> implements Record4<Integer, Short, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.sessionstats24h.idsite</code>.
     */
    public void setIdsite(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.sessionstats24h.idsite</code>.
     */
    public Integer getIdsite() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>live.sessionstats24h.hour</code>.
     */
    public void setHour(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.sessionstats24h.hour</code>.
     */
    public Short getHour() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>live.sessionstats24h.sessions</code>.
     */
    public void setSessions(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.sessionstats24h.sessions</code>.
     */
    public Long getSessions() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>live.sessionstats24h.statsrequests</code>.
     */
    public void setStatsrequests(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>live.sessionstats24h.statsrequests</code>.
     */
    public Long getStatsrequests() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Short, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Short, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sessionstats24h.SESSIONSTATS24H.IDSITE;
    }

    @Override
    public Field<Short> field2() {
        return Sessionstats24h.SESSIONSTATS24H.HOUR;
    }

    @Override
    public Field<Long> field3() {
        return Sessionstats24h.SESSIONSTATS24H.SESSIONS;
    }

    @Override
    public Field<Long> field4() {
        return Sessionstats24h.SESSIONSTATS24H.STATSREQUESTS;
    }

    @Override
    public Integer component1() {
        return getIdsite();
    }

    @Override
    public Short component2() {
        return getHour();
    }

    @Override
    public Long component3() {
        return getSessions();
    }

    @Override
    public Long component4() {
        return getStatsrequests();
    }

    @Override
    public Integer value1() {
        return getIdsite();
    }

    @Override
    public Short value2() {
        return getHour();
    }

    @Override
    public Long value3() {
        return getSessions();
    }

    @Override
    public Long value4() {
        return getStatsrequests();
    }

    @Override
    public Sessionstats24hRecord value1(Integer value) {
        setIdsite(value);
        return this;
    }

    @Override
    public Sessionstats24hRecord value2(Short value) {
        setHour(value);
        return this;
    }

    @Override
    public Sessionstats24hRecord value3(Long value) {
        setSessions(value);
        return this;
    }

    @Override
    public Sessionstats24hRecord value4(Long value) {
        setStatsrequests(value);
        return this;
    }

    @Override
    public Sessionstats24hRecord values(Integer value1, Short value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Sessionstats24hRecord
     */
    public Sessionstats24hRecord() {
        super(Sessionstats24h.SESSIONSTATS24H);
    }

    /**
     * Create a detached, initialised Sessionstats24hRecord
     */
    public Sessionstats24hRecord(Integer idsite, Short hour, Long sessions, Long statsrequests) {
        super(Sessionstats24h.SESSIONSTATS24H);

        setIdsite(idsite);
        setHour(hour);
        setSessions(sessions);
        setStatsrequests(statsrequests);
    }
}
