/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.SessionSelection;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionSelectionRecord extends TableRecordImpl<SessionSelectionRecord> implements Record1<BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.session_selection.idsession</code>.
     */
    public void setIdsession(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.session_selection.idsession</code>.
     */
    public BigDecimal getIdsession() {
        return (BigDecimal) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<BigDecimal> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<BigDecimal> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return SessionSelection.SESSION_SELECTION.IDSESSION;
    }

    @Override
    public BigDecimal component1() {
        return getIdsession();
    }

    @Override
    public BigDecimal value1() {
        return getIdsession();
    }

    @Override
    public SessionSelectionRecord value1(BigDecimal value) {
        setIdsession(value);
        return this;
    }

    @Override
    public SessionSelectionRecord values(BigDecimal value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionSelectionRecord
     */
    public SessionSelectionRecord() {
        super(SessionSelection.SESSION_SELECTION);
    }

    /**
     * Create a detached, initialised SessionSelectionRecord
     */
    public SessionSelectionRecord(BigDecimal idsession) {
        super(SessionSelection.SESSION_SELECTION);

        setIdsession(idsession);
    }
}
