/*
 * This file is generated by jOOQ.
 */
package com.verint.mpathy.db.live.tables.records;


import com.verint.mpathy.db.live.tables.VideoPageStats;

import java.math.BigDecimal;
import java.time.LocalTime;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * This table holds debugging/logging information for recordings generated by
 * the native mobile SDK.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VideoPageStatsRecord extends TableRecordImpl<VideoPageStatsRecord> implements Record14<Long, BigDecimal, BigDecimal, BigDecimal, String, String, Boolean, String, String, LocalTime, String, Short, Short, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>live.video_page_stats.idvideo_page_stats</code>. ID
     * column.
     */
    public void setIdvideoPageStats(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>live.video_page_stats.idvideo_page_stats</code>. ID
     * column.
     */
    public Long getIdvideoPageStats() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>live.video_page_stats.idvisitor</code>. References the
     * idvisitor from table visitor. No FK as entries in this table may exists
     * independently.
     */
    public void setIdvisitor(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>live.video_page_stats.idvisitor</code>. References the
     * idvisitor from table visitor. No FK as entries in this table may exists
     * independently.
     */
    public BigDecimal getIdvisitor() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>live.video_page_stats.idpage</code>. References the
     * idpage from table page. No FK as entries in this table may exists
     * independently.
     */
    public void setIdpage(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>live.video_page_stats.idpage</code>. References the
     * idpage from table page. No FK as entries in this table may exists
     * independently.
     */
    public BigDecimal getIdpage() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>live.video_page_stats.idclient</code>. References the
     * idvclient from table site. No FK as entries in this table may exists
     * independently.
     */
    public void setIdclient(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>live.video_page_stats.idclient</code>. References the
     * idvclient from table site. No FK as entries in this table may exists
     * independently.
     */
    public BigDecimal getIdclient() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>live.video_page_stats.device</code>. Holds information
     * on the recorded device.
     */
    public void setDevice(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>live.video_page_stats.device</code>. Holds information
     * on the recorded device.
     */
    public String getDevice() {
        return (String) get(4);
    }

    /**
     * Setter for <code>live.video_page_stats.stage</code>. Holds information on
     * the stage of recording, this stats entry was created.
     */
    public void setStage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>live.video_page_stats.stage</code>. Holds information on
     * the stage of recording, this stats entry was created.
     */
    public String getStage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>live.video_page_stats.success</code>. Holds information
     * on successful processing of the recording in the given stage.
     */
    public void setSuccess(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>live.video_page_stats.success</code>. Holds information
     * on successful processing of the recording in the given stage.
     */
    public Boolean getSuccess() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>live.video_page_stats.pagename</code>. Holds information
     * on the pagename, this stats entry was created in. No reference to table
     * page_name.
     */
    public void setPagename(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>live.video_page_stats.pagename</code>. Holds information
     * on the pagename, this stats entry was created in. No reference to table
     * page_name.
     */
    public String getPagename() {
        return (String) get(7);
    }

    /**
     * Setter for <code>live.video_page_stats.message</code>. Holds
     * debug/logging information.
     */
    public void setMessage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>live.video_page_stats.message</code>. Holds
     * debug/logging information.
     */
    public String getMessage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>live.video_page_stats.date</code>. Holds the date the
     * page stats was processed at.
     */
    public void setDate(LocalTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>live.video_page_stats.date</code>. Holds the date the
     * page stats was processed at.
     */
    public LocalTime getDate() {
        return (LocalTime) get(9);
    }

    /**
     * Setter for <code>live.video_page_stats.uuid</code>. Contains the uuid id
     * (version 1) to identify the video.
     */
    public void setUuid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>live.video_page_stats.uuid</code>. Contains the uuid id
     * (version 1) to identify the video.
     */
    public String getUuid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>live.video_page_stats.chunk_index</code>. The current
     * chunked position of the video part.
     */
    public void setChunkIndex(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>live.video_page_stats.chunk_index</code>. The current
     * chunked position of the video part.
     */
    public Short getChunkIndex() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>live.video_page_stats.last_chunk_index</code>. The size
     * of all chunks of the videos.
     */
    public void setLastChunkIndex(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>live.video_page_stats.last_chunk_index</code>. The size
     * of all chunks of the videos.
     */
    public Short getLastChunkIndex() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>live.video_page_stats.device_info</code>. Contains a
     * encoded json object with different device information.
     */
    public void setDeviceInfo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>live.video_page_stats.device_info</code>. Contains a
     * encoded json object with different device information.
     */
    public String getDeviceInfo() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, BigDecimal, BigDecimal, BigDecimal, String, String, Boolean, String, String, LocalTime, String, Short, Short, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, BigDecimal, BigDecimal, BigDecimal, String, String, Boolean, String, String, LocalTime, String, Short, Short, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return VideoPageStats.VIDEO_PAGE_STATS.IDVIDEO_PAGE_STATS;
    }

    @Override
    public Field<BigDecimal> field2() {
        return VideoPageStats.VIDEO_PAGE_STATS.IDVISITOR;
    }

    @Override
    public Field<BigDecimal> field3() {
        return VideoPageStats.VIDEO_PAGE_STATS.IDPAGE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return VideoPageStats.VIDEO_PAGE_STATS.IDCLIENT;
    }

    @Override
    public Field<String> field5() {
        return VideoPageStats.VIDEO_PAGE_STATS.DEVICE;
    }

    @Override
    public Field<String> field6() {
        return VideoPageStats.VIDEO_PAGE_STATS.STAGE;
    }

    @Override
    public Field<Boolean> field7() {
        return VideoPageStats.VIDEO_PAGE_STATS.SUCCESS;
    }

    @Override
    public Field<String> field8() {
        return VideoPageStats.VIDEO_PAGE_STATS.PAGENAME;
    }

    @Override
    public Field<String> field9() {
        return VideoPageStats.VIDEO_PAGE_STATS.MESSAGE;
    }

    @Override
    public Field<LocalTime> field10() {
        return VideoPageStats.VIDEO_PAGE_STATS.DATE;
    }

    @Override
    public Field<String> field11() {
        return VideoPageStats.VIDEO_PAGE_STATS.UUID;
    }

    @Override
    public Field<Short> field12() {
        return VideoPageStats.VIDEO_PAGE_STATS.CHUNK_INDEX;
    }

    @Override
    public Field<Short> field13() {
        return VideoPageStats.VIDEO_PAGE_STATS.LAST_CHUNK_INDEX;
    }

    @Override
    public Field<String> field14() {
        return VideoPageStats.VIDEO_PAGE_STATS.DEVICE_INFO;
    }

    @Override
    public Long component1() {
        return getIdvideoPageStats();
    }

    @Override
    public BigDecimal component2() {
        return getIdvisitor();
    }

    @Override
    public BigDecimal component3() {
        return getIdpage();
    }

    @Override
    public BigDecimal component4() {
        return getIdclient();
    }

    @Override
    public String component5() {
        return getDevice();
    }

    @Override
    public String component6() {
        return getStage();
    }

    @Override
    public Boolean component7() {
        return getSuccess();
    }

    @Override
    public String component8() {
        return getPagename();
    }

    @Override
    public String component9() {
        return getMessage();
    }

    @Override
    public LocalTime component10() {
        return getDate();
    }

    @Override
    public String component11() {
        return getUuid();
    }

    @Override
    public Short component12() {
        return getChunkIndex();
    }

    @Override
    public Short component13() {
        return getLastChunkIndex();
    }

    @Override
    public String component14() {
        return getDeviceInfo();
    }

    @Override
    public Long value1() {
        return getIdvideoPageStats();
    }

    @Override
    public BigDecimal value2() {
        return getIdvisitor();
    }

    @Override
    public BigDecimal value3() {
        return getIdpage();
    }

    @Override
    public BigDecimal value4() {
        return getIdclient();
    }

    @Override
    public String value5() {
        return getDevice();
    }

    @Override
    public String value6() {
        return getStage();
    }

    @Override
    public Boolean value7() {
        return getSuccess();
    }

    @Override
    public String value8() {
        return getPagename();
    }

    @Override
    public String value9() {
        return getMessage();
    }

    @Override
    public LocalTime value10() {
        return getDate();
    }

    @Override
    public String value11() {
        return getUuid();
    }

    @Override
    public Short value12() {
        return getChunkIndex();
    }

    @Override
    public Short value13() {
        return getLastChunkIndex();
    }

    @Override
    public String value14() {
        return getDeviceInfo();
    }

    @Override
    public VideoPageStatsRecord value1(Long value) {
        setIdvideoPageStats(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value2(BigDecimal value) {
        setIdvisitor(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value3(BigDecimal value) {
        setIdpage(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value4(BigDecimal value) {
        setIdclient(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value5(String value) {
        setDevice(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value6(String value) {
        setStage(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value7(Boolean value) {
        setSuccess(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value8(String value) {
        setPagename(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value9(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value10(LocalTime value) {
        setDate(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value11(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value12(Short value) {
        setChunkIndex(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value13(Short value) {
        setLastChunkIndex(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord value14(String value) {
        setDeviceInfo(value);
        return this;
    }

    @Override
    public VideoPageStatsRecord values(Long value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, String value5, String value6, Boolean value7, String value8, String value9, LocalTime value10, String value11, Short value12, Short value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VideoPageStatsRecord
     */
    public VideoPageStatsRecord() {
        super(VideoPageStats.VIDEO_PAGE_STATS);
    }

    /**
     * Create a detached, initialised VideoPageStatsRecord
     */
    public VideoPageStatsRecord(Long idvideoPageStats, BigDecimal idvisitor, BigDecimal idpage, BigDecimal idclient, String device, String stage, Boolean success, String pagename, String message, LocalTime date, String uuid, Short chunkIndex, Short lastChunkIndex, String deviceInfo) {
        super(VideoPageStats.VIDEO_PAGE_STATS);

        setIdvideoPageStats(idvideoPageStats);
        setIdvisitor(idvisitor);
        setIdpage(idpage);
        setIdclient(idclient);
        setDevice(device);
        setStage(stage);
        setSuccess(success);
        setPagename(pagename);
        setMessage(message);
        setDate(date);
        setUuid(uuid);
        setChunkIndex(chunkIndex);
        setLastChunkIndex(lastChunkIndex);
        setDeviceInfo(deviceInfo);
    }
}
